// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListArchiveFilesWireQuery = NonNullable<paths["/archive_files"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listArchiveFiles}. */
export interface ListArchiveFilesQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListArchiveFilesWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListArchiveFilesWireQuery["next_page_token"]>;

	/** The query start date, in `yyyy-MM-dd'T'HH:mm:ssZ` format. This value and the `to` query parameter value cannot exceed seven days. */
	readonly from?: Sendable<ListArchiveFilesWireQuery["from"]>;

	/** The query end date, in `yyyy-MM-dd'T'HH:mm:ssZ` format. This value and the `from` query parameter value cannot exceed seven days. */
	readonly to?: Sendable<ListArchiveFilesWireQuery["to"]>;

	/**
	 * The type of query date.
	 * * `meeting_start_time` 
	 * * `archive_complete_time` 
	 *
	 *  This value defaults to `meeting_start_time`.
	 */
	readonly queryDateType?: Sendable<ListArchiveFilesWireQuery["query_date_type"]>;

	/** Deprecated. Please use 'group_ids' for querying. */
	readonly groupId?: Sendable<ListArchiveFilesWireQuery["group_id"]>;

	/**
	 * The group IDs. To get a group ID, use the [List groups](/docs/api/rest/reference/scim-api/methods/#operation/groupSCIM2List) API.
	 * (The maximum number of supported groups for filtering is 7.)
	 */
	readonly groupIds?: Sendable<ListArchiveFilesWireQuery["group_ids"]>;
}

/** What {@link listArchiveFiles} resolves to. */
export type ListArchiveFilesResponse =
	paths["/archive_files"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /archive_files`
 *
 * List archived files
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read:admin` `archiving:read:list_archived_files:admin` `archiving:read:list_archived_files:master` and openapi_authorization: header `Authorization`
 */
export function listArchiveFiles(
	query: ListArchiveFilesQuery = {},
): Operation<ListArchiveFilesResponse> {
	return {
		method: "GET",
		path: "/archive_files",
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			from: query.from,
			to: query.to,
			query_date_type: query.queryDateType,
			group_id: query.groupId,
			group_ids: query.groupIds,
		},
	};
}

type GetArchiveFileDownloadAuditWireQuery = NonNullable<paths["/archive_files/download_audit"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getArchiveFileDownloadAudit}. */
export interface GetArchiveFileDownloadAuditQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<GetArchiveFileDownloadAuditWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<GetArchiveFileDownloadAuditWireQuery["next_page_token"]>;

	/** The query start date, in `yyyy-MM-dd'T'HH:mm:ssZ` format. This value and the `to` query parameter value cannot exceed seven days. */
	readonly from?: Sendable<GetArchiveFileDownloadAuditWireQuery["from"]>;

	/** The query end date, in `yyyy-MM-dd'T'HH:mm:ssZ` format. This value and the `from` query parameter value cannot exceed seven days. */
	readonly to?: Sendable<GetArchiveFileDownloadAuditWireQuery["to"]>;
}

/** What {@link getArchiveFileDownloadAudit} resolves to. */
export type GetArchiveFileDownloadAuditResponse =
	paths["/archive_files/download_audit"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /archive_files/download_audit`
 *
 * List archived file download audit logs
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>` and openapi_authorization: header `Authorization`
 */
export function getArchiveFileDownloadAudit(
	query: GetArchiveFileDownloadAuditQuery = {},
): Operation<GetArchiveFileDownloadAuditResponse> {
	return {
		method: "GET",
		path: "/archive_files/download_audit",
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			from: query.from,
			to: query.to,
		},
	};
}

type ListArchiveFileStatisticsWireQuery = NonNullable<paths["/archive_files/statistics"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listArchiveFileStatistics}. */
export interface ListArchiveFileStatisticsQuery {
	/** The query start date, in `yyyy-MM-dd'T'HH:mm:ssZ` format. This value and the `to` query parameter value cannot exceed seven days. */
	readonly from?: Sendable<ListArchiveFileStatisticsWireQuery["from"]>;

	/** The query end date, in `yyyy-MM-dd'T'HH:mm:ssZ` format. This value and the `from` query parameter value cannot exceed seven days. */
	readonly to?: Sendable<ListArchiveFileStatisticsWireQuery["to"]>;
}

/** What {@link listArchiveFileStatistics} resolves to. */
export type ListArchiveFileStatisticsResponse =
	paths["/archive_files/statistics"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /archive_files/statistics`
 *
 * Get archived file statistics
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read:admin` `archiving:read:archived_file_statistics:admin` and openapi_authorization: header `Authorization`
 */
export function listArchiveFileStatistics(
	query: ListArchiveFileStatisticsQuery = {},
): Operation<ListArchiveFileStatisticsResponse> {
	return {
		method: "GET",
		path: "/archive_files/statistics",
		query: {
			from: query.from,
			to: query.to,
		},
	};
}

type UpdateArchiveFileWirePath = NonNullable<paths["/archive_files/{fileId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateArchiveFile}. */
export type UpdateArchiveFileBody = NonNullable<paths["/archive_files/{fileId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /archive_files/{fileId}`
 *
 * Update an archived file's auto-delete status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write` `recording:write:admin` `archiving:update:archived_file_auto_delete_status` `archiving:update:archived_file_auto_delete_status:admin` and openapi_authorization: header `Authorization`
 */
export function updateArchiveFile(
	fileId: UpdateArchiveFileWirePath["fileId"],
	patch: UpdateArchiveFileBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/archive_files/${encodeURIComponent(String(fileId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}
