// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListDevicesWireQuery = NonNullable<paths["/devices"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listDevices}. */
export interface ListDevicesQuery {
	/** Filter devices by name or serial number. */
	readonly searchText?: Sendable<ListDevicesWireQuery["search_text"]>;

	/** Filter devices by platform operating system. */
	readonly platformOs?: Sendable<ListDevicesWireQuery["platform_os"]>;

	/** Filter devices by enrollment of ZDM (Zoom Device Management). */
	readonly isEnrolledInZdm?: Sendable<ListDevicesWireQuery["is_enrolled_in_zdm"]>;

	/**
	 * Filter devices by device type.  
	 *  `-1` — All Zoom Room devices (0,1,2,3,4,6).  
	 *  `0` — Zoom Rooms computer.  
	 *  `1` — Zoom Rooms controller.  
	 *  `2` — Zoom Rooms scheduling display.  
	 *  `3` — Zoom Rooms control system.  
	 *  `4` — Zoom Rooms whiteboard.  
	 *  `5` — Zoom Phone appliance.  
	 *  `6` — Zoom Rooms computer with controller.  
	 *  `7` — Workspace devices.  
	 *  `8` — Zoom clients.  
	 *  `9` — Zoom VDI clients.
	 */
	readonly deviceType?: Sendable<ListDevicesWireQuery["device_type"]>;

	/** Filter devices by vendor. */
	readonly deviceVendor?: Sendable<ListDevicesWireQuery["device_vendor"]>;

	/** Filter devices by model. */
	readonly deviceModel?: Sendable<ListDevicesWireQuery["device_model"]>;

	/**
	 * Filter devices by status.   
	 *   Device Status:  
	 *  `0` - offline.  
	 *  `1` - online.  
	 *  `-1` - unlink
	 */
	readonly deviceStatus?: Sendable<ListDevicesWireQuery["device_status"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListDevicesWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListDevicesWireQuery["next_page_token"]>;
}

/** What {@link listDevices} resolves to. */
export type ListDevicesResponse =
	paths["/devices"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /devices`
 *
 * List devices
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:read:admin` `device:write:admin` and openapi_authorization: header `Authorization`
 */
export function listDevices(
	query: ListDevicesQuery = {},
): Operation<ListDevicesResponse> {
	return {
		method: "GET",
		path: "/devices",
		query: {
			search_text: query.searchText,
			platform_os: query.platformOs,
			is_enrolled_in_zdm: query.isEnrolledInZdm,
			device_type: query.deviceType,
			device_vendor: query.deviceVendor,
			device_model: query.deviceModel,
			device_status: query.deviceStatus,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

/** Body accepted by {@link createDevice}. */
export type CreateDeviceBody = NonNullable<paths["/devices"]["post"]["requestBody"]>["content"]["application/json"];

/**
 * `POST /devices`
 *
 * Add a new device
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` and openapi_authorization: header `Authorization`
 */
export function createDevice(input: CreateDeviceBody): Operation<void> {
	return {
		method: "POST",
		path: "/devices",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type ListDeviceGroupsWireQuery = NonNullable<paths["/devices/groups"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listDeviceGroups}. */
export interface ListDeviceGroupsQuery {
	/**
	 * The total number of records returned from a single API call.
	 * Default - 30.
	 * Max -100.
	 */
	readonly pageSize?: Sendable<ListDeviceGroupsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period token is 15 minutes. */
	readonly nextPageToken?: Sendable<ListDeviceGroupsWireQuery["next_page_token"]>;
}

/** What {@link listDeviceGroups} resolves to. */
export type ListDeviceGroupsResponse =
	paths["/devices/groups"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /devices/groups`
 *
 * Get ZDM group info
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:read:admin` `device:read:list_groups:admin` `device:read:list_groups:master` and openapi_authorization: header `Authorization`
 */
export function listDeviceGroups(
	query: ListDeviceGroupsQuery = {},
): Operation<ListDeviceGroupsResponse> {
	return {
		method: "GET",
		path: "/devices/groups",
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

/** Body accepted by {@link updateDeviceZpaAssignment}. */
export type UpdateDeviceZpaAssignmentBody = NonNullable<paths["/devices/zpa/assignment"]["post"]["requestBody"]>["content"]["application/json"];

/**
 * `POST /devices/zpa/assignment`
 *
 * Assign a device to a user or commonarea
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` `device:write:zpa_device:admin` `device:write:zpa_device:master` and openapi_authorization: header `Authorization`
 */
export function updateDeviceZpaAssignment(
	input: UpdateDeviceZpaAssignmentBody,
): Operation<void> {
	return {
		method: "POST",
		path: "/devices/zpa/assignment",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type ListDeviceZpaSettingsWireQuery = NonNullable<paths["/devices/zpa/settings"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listDeviceZpaSettings}. */
export interface ListDeviceZpaSettingsQuery {
	/** The user's ID or email address. For user-level apps, pass `me` as the value for `user_id`. */
	readonly userId?: Sendable<ListDeviceZpaSettingsWireQuery["user_id"]>;
}

/** What {@link listDeviceZpaSettings} resolves to. */
export type ListDeviceZpaSettingsResponse =
	paths["/devices/zpa/settings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /devices/zpa/settings`
 *
 * Get Zoom Phone Appliance settings by user ID
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:read:admin` `device:read:user_setting:admin` `device:read:user_setting:master` and openapi_authorization: header `Authorization`
 */
export function listDeviceZpaSettings(
	query: ListDeviceZpaSettingsQuery = {},
): Operation<ListDeviceZpaSettingsResponse> {
	return {
		method: "GET",
		path: "/devices/zpa/settings",
		query: {
			user_id: query.userId,
		},
	};
}

/** Body accepted by {@link updateDeviceZpaUpgrade}. */
export type UpdateDeviceZpaUpgradeBody = NonNullable<paths["/devices/zpa/upgrade"]["post"]["requestBody"]>["content"]["application/json"];

/**
 * `POST /devices/zpa/upgrade`
 *
 * Upgrade ZPA firmware or app
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` `device:write:zpa_os_app:admin` `device:write:zpa_os_app:master` and openapi_authorization: header `Authorization`
 */
export function updateDeviceZpaUpgrade(
	input: UpdateDeviceZpaUpgradeBody,
): Operation<void> {
	return {
		method: "POST",
		path: "/devices/zpa/upgrade",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type DeleteDeviceZpaVendorMacAddressWirePath = NonNullable<paths["/devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}`
 *
 * Delete ZPA device by vendor and mac address
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` `device:delete:zpa_device:admin` `device:delete:zpa_device:master` and openapi_authorization: header `Authorization`
 */
export function deleteDeviceZpaVendorMacAddress(
	vendor: DeleteDeviceZpaVendorMacAddressWirePath["vendor"],
	macAddress: DeleteDeviceZpaVendorMacAddressWirePath["macAddress"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/devices/zpa/vendors/${encodeURIComponent(String(vendor))}/mac_addresses/${encodeURIComponent(String(macAddress))}`,
		decode: async () => undefined,
	};
}

type ListDeviceZpaZdmGroupVersionsWirePath = NonNullable<paths["/devices/zpa/zdm_groups/{zdmGroupId}/versions"]["get"]["parameters"]["path"]>;

/** What {@link listDeviceZpaZdmGroupVersions} resolves to. */
export type ListDeviceZpaZdmGroupVersionsResponse =
	paths["/devices/zpa/zdm_groups/{zdmGroupId}/versions"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /devices/zpa/zdm_groups/{zdmGroupId}/versions`
 *
 * Get ZPA version info
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:read:admin` `device:read:list_zpa_versions:admin` `device:read:list_zpa_versions:master` and openapi_authorization: header `Authorization`
 */
export function listDeviceZpaZdmGroupVersions(
	zdmGroupId: ListDeviceZpaZdmGroupVersionsWirePath["zdmGroupId"],
): Operation<ListDeviceZpaZdmGroupVersionsResponse> {
	return {
		method: "GET",
		path: `/devices/zpa/zdm_groups/${encodeURIComponent(String(zdmGroupId))}/versions`,
	};
}

type GetDeviceWirePath = NonNullable<paths["/devices/{deviceId}"]["get"]["parameters"]["path"]>;

/** What {@link getDevice} resolves to. */
export type GetDeviceResponse =
	paths["/devices/{deviceId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /devices/{deviceId}`
 *
 * Get device detail
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:read:admin` `device:write:admin` and openapi_authorization: header `Authorization`
 */
export function getDevice(
	deviceId: GetDeviceWirePath["deviceId"],
): Operation<GetDeviceResponse> {
	return {
		method: "GET",
		path: `/devices/${encodeURIComponent(String(deviceId))}`,
	};
}

type UpdateDeviceWirePath = NonNullable<paths["/devices/{deviceId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateDevice}. */
export type UpdateDeviceBody = NonNullable<paths["/devices/{deviceId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /devices/{deviceId}`
 *
 * Change device 
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` and openapi_authorization: header `Authorization`
 */
export function updateDevice(
	deviceId: UpdateDeviceWirePath["deviceId"],
	patch: UpdateDeviceBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/devices/${encodeURIComponent(String(deviceId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteDeviceWirePath = NonNullable<paths["/devices/{deviceId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /devices/{deviceId}`
 *
 * Delete device
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` and openapi_authorization: header `Authorization`
 */
export function deleteDevice(
	deviceId: DeleteDeviceWirePath["deviceId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/devices/${encodeURIComponent(String(deviceId))}`,
		decode: async () => undefined,
	};
}

type UpdateDeviceAssignGroupWirePath = NonNullable<paths["/devices/{deviceId}/assign_group"]["patch"]["parameters"]["path"]>;

type UpdateDeviceAssignGroupWireQuery = NonNullable<paths["/devices/{deviceId}/assign_group"]["patch"]["parameters"]["query"]>;

/** Query accepted by {@link updateDeviceAssignGroup}. */
export interface UpdateDeviceAssignGroupQuery {
	/** The group's ID. */
	readonly groupId: Sendable<UpdateDeviceAssignGroupWireQuery["group_id"]>;
}

/**
 * `PATCH /devices/{deviceId}/assign_group`
 *
 * Assign a device to a group
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` `device:write:group:admin` `device:write:group:master` and openapi_authorization: header `Authorization`
 */
export function updateDeviceAssignGroup(
	deviceId: UpdateDeviceAssignGroupWirePath["deviceId"],
	query: UpdateDeviceAssignGroupQuery,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/devices/${encodeURIComponent(String(deviceId))}/assign_group`,
		query: {
			group_id: query.groupId,
		},
		decode: async () => undefined,
	};
}

type UpdateDeviceAssignmentWirePath = NonNullable<paths["/devices/{deviceId}/assignment"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateDeviceAssignment}. */
export type UpdateDeviceAssignmentBody = NonNullable<paths["/devices/{deviceId}/assignment"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /devices/{deviceId}/assignment`
 *
 * Change device association
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `device:write:admin` `device:update:zdm_device_assignment:admin` and openapi_authorization: header `Authorization`
 */
export function updateDeviceAssignment(
	deviceId: UpdateDeviceAssignmentWirePath["deviceId"],
	patch: UpdateDeviceAssignmentBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/devices/${encodeURIComponent(String(deviceId))}/assignment`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}
