// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListH323DevicesWireQuery = NonNullable<paths["/h323/devices"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listH323Devices}. */
export interface ListH323DevicesQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListH323DevicesWireQuery["page_size"]>;

	/** **Deprecated.** We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination. */
	readonly pageNumber?: Sendable<ListH323DevicesWireQuery["page_number"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListH323DevicesWireQuery["next_page_token"]>;
}

/** What {@link listH323Devices} resolves to. */
export type ListH323DevicesResponse =
	paths["/h323/devices"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /h323/devices`
 *
 * List H.323/SIP devices
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `h323:read:admin` `h323_device:read:list_devices:admin` and openapi_authorization: header `Authorization`
 */
export function listH323Devices(
	query: ListH323DevicesQuery = {},
): Operation<ListH323DevicesResponse> {
	return {
		method: "GET",
		path: "/h323/devices",
		query: {
			page_size: query.pageSize,
			page_number: query.pageNumber,
			next_page_token: query.nextPageToken,
		},
	};
}

/** Body accepted by {@link createH323Device}. */
export type CreateH323DeviceBody = NonNullable<paths["/h323/devices"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createH323Device} resolves to. */
export type CreateH323DeviceResponse =
	paths["/h323/devices"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /h323/devices`
 *
 * Create a H.323/SIP device
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `h323:write:admin` `h323_device:write:device:admin` and openapi_authorization: header `Authorization`
 */
export function createH323Device(
	input: CreateH323DeviceBody,
): Operation<CreateH323DeviceResponse> {
	return {
		method: "POST",
		path: "/h323/devices",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type UpdateH323DeviceWirePath = NonNullable<paths["/h323/devices/{deviceId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateH323Device}. */
export type UpdateH323DeviceBody = NonNullable<paths["/h323/devices/{deviceId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /h323/devices/{deviceId}`
 *
 * Update a H.323/SIP device
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `h323:write:admin` `h323_device:update:device:admin` and openapi_authorization: header `Authorization`
 */
export function updateH323Device(
	deviceId: UpdateH323DeviceWirePath["deviceId"],
	patch: UpdateH323DeviceBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/h323/devices/${encodeURIComponent(String(deviceId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteH323DeviceWirePath = NonNullable<paths["/h323/devices/{deviceId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /h323/devices/{deviceId}`
 *
 * Delete a H.323/SIP device
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `h323:write:admin` `h323_device:delete:device:admin` and openapi_authorization: header `Authorization`
 */
export function deleteH323Device(
	deviceId: DeleteH323DeviceWirePath["deviceId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/h323/devices/${encodeURIComponent(String(deviceId))}`,
		decode: async () => undefined,
	};
}
