// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type DeleteLiveWebinarChatMessageWirePath = NonNullable<paths["/live_webinars/{webinarId}/chat/messages/{messageId}"]["delete"]["parameters"]["path"]>;

type DeleteLiveWebinarChatMessageWireQuery = NonNullable<paths["/live_webinars/{webinarId}/chat/messages/{messageId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteLiveWebinarChatMessage}. */
export interface DeleteLiveWebinarChatMessageQuery {
	/** The live webinar chat file's universally unique identifier (UUID), in base64-encoded format. Separate multiple values with commas. */
	readonly fileIds?: Sendable<DeleteLiveWebinarChatMessageWireQuery["file_ids"]>;
}

/**
 * `DELETE /live_webinars/{webinarId}/chat/messages/{messageId}`
 *
 * Delete a live webinar message
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:delete:live_webinar_chat_message` `webinar:delete:live_webinar_chat_message:admin` and openapi_authorization: header `Authorization`
 */
export function deleteLiveWebinarChatMessage(
	webinarId: DeleteLiveWebinarChatMessageWirePath["webinarId"],
	messageId: DeleteLiveWebinarChatMessageWirePath["messageId"],
	query: DeleteLiveWebinarChatMessageQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/live_webinars/${encodeURIComponent(String(webinarId))}/chat/messages/${encodeURIComponent(String(messageId))}`,
		query: {
			file_ids: query.fileIds,
		},
		decode: async () => undefined,
	};
}
