// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type UpdateLiveMeetingChatMessageWirePath = NonNullable<paths["/live_meetings/{meetingId}/chat/messages/{messageId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateLiveMeetingChatMessage}. */
export type UpdateLiveMeetingChatMessageBody = NonNullable<paths["/live_meetings/{meetingId}/chat/messages/{messageId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /live_meetings/{meetingId}/chat/messages/{messageId}`
 *
 * Update a live meeting message
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:update:live_meeting_chat_message` `meeting:update:live_meeting_chat_message:admin` and openapi_authorization: header `Authorization`
 */
export function updateLiveMeetingChatMessage(
	meetingId: UpdateLiveMeetingChatMessageWirePath["meetingId"],
	messageId: UpdateLiveMeetingChatMessageWirePath["messageId"],
	patch: UpdateLiveMeetingChatMessageBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/live_meetings/${encodeURIComponent(String(meetingId))}/chat/messages/${encodeURIComponent(String(messageId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteLiveMeetingChatMessageWirePath = NonNullable<paths["/live_meetings/{meetingId}/chat/messages/{messageId}"]["delete"]["parameters"]["path"]>;

type DeleteLiveMeetingChatMessageWireQuery = NonNullable<paths["/live_meetings/{meetingId}/chat/messages/{messageId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteLiveMeetingChatMessage}. */
export interface DeleteLiveMeetingChatMessageQuery {
	/** The live webinar chat file's universally unique identifier, in base64-encoded format. Separate multiple values with commas. */
	readonly fileIds?: Sendable<DeleteLiveMeetingChatMessageWireQuery["file_ids"]>;
}

/**
 * `DELETE /live_meetings/{meetingId}/chat/messages/{messageId}`
 *
 * Delete a live meeting message
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:delete:live_meeting_chat_message` `meeting:delete:live_meeting_chat_message:admin` and openapi_authorization: header `Authorization`
 */
export function deleteLiveMeetingChatMessage(
	meetingId: DeleteLiveMeetingChatMessageWirePath["meetingId"],
	messageId: DeleteLiveMeetingChatMessageWirePath["messageId"],
	query: DeleteLiveMeetingChatMessageQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/live_meetings/${encodeURIComponent(String(meetingId))}/chat/messages/${encodeURIComponent(String(messageId))}`,
		query: {
			file_ids: query.fileIds,
		},
		decode: async () => undefined,
	};
}

type UpdateLiveMeetingEventsWirePath = NonNullable<paths["/live_meetings/{meetingId}/events"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateLiveMeetingEvents}. */
export type UpdateLiveMeetingEventsBody = NonNullable<paths["/live_meetings/{meetingId}/events"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /live_meetings/{meetingId}/events`
 *
 * In-meeting controls
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:master` `meeting:update:in_meeting_controls` `meeting:update:in_meeting_controls:admin` and openapi_authorization: header `Authorization`
 */
export function updateLiveMeetingEvents(
	meetingId: UpdateLiveMeetingEventsWirePath["meetingId"],
	patch: UpdateLiveMeetingEventsBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/live_meetings/${encodeURIComponent(String(meetingId))}/events`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type UpdateLiveMeetingRtmsAppStatusWirePath = NonNullable<paths["/live_meetings/{meetingId}/rtms_app/status"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateLiveMeetingRtmsAppStatus}. */
export type UpdateLiveMeetingRtmsAppStatusBody = NonNullable<paths["/live_meetings/{meetingId}/rtms_app/status"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /live_meetings/{meetingId}/rtms_app/status`
 *
 * Update participant Real-Time Media Streams (RTMS) app status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:update:participant_rtms_app_status` `meeting:update:participant_rtms_app_status:admin` and openapi_authorization: header `Authorization`
 */
export function updateLiveMeetingRtmsAppStatus(
	meetingId: UpdateLiveMeetingRtmsAppStatusWirePath["meetingId"],
	patch: UpdateLiveMeetingRtmsAppStatusBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/live_meetings/${encodeURIComponent(String(meetingId))}/rtms_app/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}
