// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListMeetingMeetingSummariesWireQuery = NonNullable<paths["/meetings/meeting_summaries"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listMeetingMeetingSummaries}. */
export interface ListMeetingMeetingSummariesQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListMeetingMeetingSummariesWireQuery["page_size"]>;

	/** Use the next page token to paginate through a large set of results. The next page token returns whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListMeetingMeetingSummariesWireQuery["next_page_token"]>;

	/** The start date, in `yyyy-MM-dd'T'HH:mm:ss'Z'` UTC format. The time field used for filtering is specified by `time_filter_field`. */
	readonly from?: Sendable<ListMeetingMeetingSummariesWireQuery["from"]>;

	/** The end date, in `yyyy-MM-dd'T'HH:mm:ss'Z'` UTC format. The time field used for filtering is specified by `time_filter_field`. */
	readonly to?: Sendable<ListMeetingMeetingSummariesWireQuery["to"]>;

	/** Which summary time field to use to filter results by the `from` and `to` parameters. */
	readonly timeFilterField?: Sendable<ListMeetingMeetingSummariesWireQuery["time_filter_field"]>;
}

/** What {@link listMeetingMeetingSummaries} resolves to. */
export type ListMeetingMeetingSummariesResponse =
	paths["/meetings/meeting_summaries"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/meeting_summaries`
 *
 * List an account's meeting or webinar summaries
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_summary:read:admin` `meeting:read:list_summaries:admin` and openapi_authorization: header `Authorization`
 */
export function listMeetingMeetingSummaries(
	query: ListMeetingMeetingSummariesQuery = {},
): Operation<ListMeetingMeetingSummariesResponse> {
	return {
		method: "GET",
		path: "/meetings/meeting_summaries",
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			from: query.from,
			to: query.to,
			time_filter_field: query.timeFilterField,
		},
	};
}

type GetMeetingWirePath = NonNullable<paths["/meetings/{meetingId}"]["get"]["parameters"]["path"]>;

type GetMeetingWireQuery = NonNullable<paths["/meetings/{meetingId}"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getMeeting}. */
export interface GetMeetingQuery {
	/** Meeting occurrence ID. Provide this field to view meeting details of a particular occurrence of the [recurring meeting](https://support.zoom.us/hc/en-us/articles/214973206-Scheduling-Recurring-Meetings). */
	readonly occurrenceId?: Sendable<GetMeetingWireQuery["occurrence_id"]>;

	/** Set this field's value to `true` to view meeting details of all previous occurrences of a [recurring meeting](https://support.zoom.us/hc/en-us/articles/214973206-Scheduling-Recurring-Meetings).  */
	readonly showPreviousOccurrences?: Sendable<GetMeetingWireQuery["show_previous_occurrences"]>;
}

/** What {@link getMeeting} resolves to. */
export type GetMeetingResponse =
	paths["/meetings/{meetingId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}`
 *
 * Get a meeting
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:meeting` `meeting:read:meeting:admin` and openapi_authorization: header `Authorization`
 */
export function getMeeting(
	meetingId: GetMeetingWirePath["meetingId"],
	query: GetMeetingQuery = {},
): Operation<GetMeetingResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}`,
		query: {
			occurrence_id: query.occurrenceId,
			show_previous_occurrences: query.showPreviousOccurrences,
		},
	};
}

type UpdateMeetingWirePath = NonNullable<paths["/meetings/{meetingId}"]["patch"]["parameters"]["path"]>;

type UpdateMeetingWireQuery = NonNullable<paths["/meetings/{meetingId}"]["patch"]["parameters"]["query"]>;

/** Query accepted by {@link updateMeeting}. */
export interface UpdateMeetingQuery {
	/** Meeting occurrence ID. Support change of agenda, `start_time`, duration, or settings {`host_video`, `participant_video`, `join_before_host`, `mute_upon_entry`, `waiting_room`, `watermark`, `auto_recording`}. */
	readonly occurrenceId?: Sendable<UpdateMeetingWireQuery["occurrence_id"]>;
}

/** Body accepted by {@link updateMeeting}. */
export type UpdateMeetingBody = NonNullable<paths["/meetings/{meetingId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}`
 *
 * Update a meeting
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:update:meeting:admin` `meeting:update:meeting` and openapi_authorization: header `Authorization`
 */
export function updateMeeting(
	meetingId: UpdateMeetingWirePath["meetingId"],
	patch: UpdateMeetingBody,
	query: UpdateMeetingQuery = {},
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}`,
		query: {
			occurrence_id: query.occurrenceId,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteMeetingWirePath = NonNullable<paths["/meetings/{meetingId}"]["delete"]["parameters"]["path"]>;

type DeleteMeetingWireQuery = NonNullable<paths["/meetings/{meetingId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteMeeting}. */
export interface DeleteMeetingQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<DeleteMeetingWireQuery["occurrence_id"]>;

	/**
	 * `true`: Notify host and alternative host about the meeting cancellation via email.
	 * `false`: Do not send any email notification.
	 */
	readonly scheduleForReminder?: Sendable<DeleteMeetingWireQuery["schedule_for_reminder"]>;

	/**
	 * `true`: Notify registrants about the meeting cancellation via email. 
	 *
	 * `false`: Do not send any email notification to meeting registrants. 
	 *
	 * The default value of this field is `false`.
	 */
	readonly cancelMeetingReminder?: Sendable<DeleteMeetingWireQuery["cancel_meeting_reminder"]>;
}

/**
 * `DELETE /meetings/{meetingId}`
 *
 * Delete a meeting
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:delete:meeting` `meeting:delete:meeting:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeeting(
	meetingId: DeleteMeetingWirePath["meetingId"],
	query: DeleteMeetingQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}`,
		query: {
			occurrence_id: query.occurrenceId,
			schedule_for_reminder: query.scheduleForReminder,
			cancel_meeting_reminder: query.cancelMeetingReminder,
		},
		decode: async () => undefined,
	};
}

type CreateMeetingBatchPollWirePath = NonNullable<paths["/meetings/{meetingId}/batch_polls"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createMeetingBatchPoll}. */
export type CreateMeetingBatchPollBody = NonNullable<paths["/meetings/{meetingId}/batch_polls"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingBatchPoll} resolves to. */
export type CreateMeetingBatchPollResponse =
	paths["/meetings/{meetingId}/batch_polls"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/batch_polls`
 *
 * Perform batch poll creation
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:write:batch_polls` `meeting:write:batch_polls:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingBatchPoll(
	meetingId: CreateMeetingBatchPollWirePath["meetingId"],
	input: CreateMeetingBatchPollBody,
): Operation<CreateMeetingBatchPollResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/batch_polls`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type CreateMeetingBatchRegistrantWirePath = NonNullable<paths["/meetings/{meetingId}/batch_registrants"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createMeetingBatchRegistrant}. */
export type CreateMeetingBatchRegistrantBody = NonNullable<paths["/meetings/{meetingId}/batch_registrants"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingBatchRegistrant} resolves to. */
export type CreateMeetingBatchRegistrantResponse =
	paths["/meetings/{meetingId}/batch_registrants"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/batch_registrants`
 *
 * Perform batch registration
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:write:batch_registrants` `meeting:write:batch_registrants:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingBatchRegistrant(
	meetingId: CreateMeetingBatchRegistrantWirePath["meetingId"],
	input: CreateMeetingBatchRegistrantBody,
): Operation<CreateMeetingBatchRegistrantResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/batch_registrants`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetMeetingInvitationWirePath = NonNullable<paths["/meetings/{meetingId}/invitation"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingInvitation} resolves to. */
export type GetMeetingInvitationResponse =
	paths["/meetings/{meetingId}/invitation"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/invitation`
 *
 * Get meeting invitation
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:invitation` `meeting:read:invitation:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingInvitation(
	meetingId: GetMeetingInvitationWirePath["meetingId"],
): Operation<GetMeetingInvitationResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/invitation`,
	};
}

type CreateMeetingInviteLinkWirePath = NonNullable<paths["/meetings/{meetingId}/invite_links"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createMeetingInviteLink}. */
export type CreateMeetingInviteLinkBody = NonNullable<paths["/meetings/{meetingId}/invite_links"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingInviteLink} resolves to. */
export type CreateMeetingInviteLinkResponse =
	paths["/meetings/{meetingId}/invite_links"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/invite_links`
 *
 * Create a meeting's invite links
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:write:invite_links` `meeting:write:invite_links:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingInviteLink(
	meetingId: CreateMeetingInviteLinkWirePath["meetingId"],
	input: CreateMeetingInviteLinkBody,
): Operation<CreateMeetingInviteLinkResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/invite_links`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetMeetingJointokenLiveStreamingWirePath = NonNullable<paths["/meetings/{meetingId}/jointoken/live_streaming"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingJointokenLiveStreaming} resolves to. */
export type GetMeetingJointokenLiveStreamingResponse =
	paths["/meetings/{meetingId}/jointoken/live_streaming"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/jointoken/live_streaming`
 *
 * Get a meeting's join token for live streaming
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_token:read:admin:live_streaming` `meeting_token:read:live_streaming` `meeting:read:live_streaming_token` `meeting:read:live_streaming_token:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingJointokenLiveStreaming(
	meetingId: GetMeetingJointokenLiveStreamingWirePath["meetingId"],
): Operation<GetMeetingJointokenLiveStreamingResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/jointoken/live_streaming`,
	};
}

type GetMeetingJointokenLocalArchivingWirePath = NonNullable<paths["/meetings/{meetingId}/jointoken/local_archiving"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingJointokenLocalArchiving} resolves to. */
export type GetMeetingJointokenLocalArchivingResponse =
	paths["/meetings/{meetingId}/jointoken/local_archiving"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/jointoken/local_archiving`
 *
 * Get a meeting's archive token for local archiving
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_token:read:admin:local_archiving` `meeting:read:local_archiving_token:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingJointokenLocalArchiving(
	meetingId: GetMeetingJointokenLocalArchivingWirePath["meetingId"],
): Operation<GetMeetingJointokenLocalArchivingResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/jointoken/local_archiving`,
	};
}

type GetMeetingJointokenLocalRecordingWirePath = NonNullable<paths["/meetings/{meetingId}/jointoken/local_recording"]["get"]["parameters"]["path"]>;

type GetMeetingJointokenLocalRecordingWireQuery = NonNullable<paths["/meetings/{meetingId}/jointoken/local_recording"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getMeetingJointokenLocalRecording}. */
export interface GetMeetingJointokenLocalRecordingQuery {
	/** Whether to bypass the waiting room. */
	readonly bypassWaitingRoom?: Sendable<GetMeetingJointokenLocalRecordingWireQuery["bypass_waiting_room"]>;
}

/** What {@link getMeetingJointokenLocalRecording} resolves to. */
export type GetMeetingJointokenLocalRecordingResponse =
	paths["/meetings/{meetingId}/jointoken/local_recording"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/jointoken/local_recording`
 *
 * Get a meeting's join token for local recording
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_token:read:admin:local_recording` `meeting_token:read:local_recording` `meeting:read:local_recording_token` `meeting:read:local_recording_token:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingJointokenLocalRecording(
	meetingId: GetMeetingJointokenLocalRecordingWirePath["meetingId"],
	query: GetMeetingJointokenLocalRecordingQuery = {},
): Operation<GetMeetingJointokenLocalRecordingResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/jointoken/local_recording`,
		query: {
			bypass_waiting_room: query.bypassWaitingRoom,
		},
	};
}

type GetMeetingLivestreamWirePath = NonNullable<paths["/meetings/{meetingId}/livestream"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingLivestream} resolves to. */
export type GetMeetingLivestreamResponse =
	paths["/meetings/{meetingId}/livestream"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/livestream`
 *
 * Get livestream details
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:livestream` `meeting:read:livestream:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingLivestream(
	meetingId: GetMeetingLivestreamWirePath["meetingId"],
): Operation<GetMeetingLivestreamResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/livestream`,
	};
}

type UpdateMeetingLivestreamWirePath = NonNullable<paths["/meetings/{meetingId}/livestream"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateMeetingLivestream}. */
export type UpdateMeetingLivestreamBody = NonNullable<paths["/meetings/{meetingId}/livestream"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}/livestream`
 *
 * Update a livestream
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:update:livestream` `meeting:update:livestream:admin` and openapi_authorization: header `Authorization`
 */
export function updateMeetingLivestream(
	meetingId: UpdateMeetingLivestreamWirePath["meetingId"],
	patch: UpdateMeetingLivestreamBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/livestream`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type UpdateMeetingLivestreamStatusWirePath = NonNullable<paths["/meetings/{meetingId}/livestream/status"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateMeetingLivestreamStatus}. */
export type UpdateMeetingLivestreamStatusBody = NonNullable<paths["/meetings/{meetingId}/livestream/status"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}/livestream/status`
 *
 * Update livestream status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:update:livestream_status` `meeting:update:livestream_status:admin` and openapi_authorization: header `Authorization`
 */
export function updateMeetingLivestreamStatus(
	meetingId: UpdateMeetingLivestreamStatusWirePath["meetingId"],
	patch: UpdateMeetingLivestreamStatusBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/livestream/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type GetMeetingMeetingSummaryWirePath = NonNullable<paths["/meetings/{meetingId}/meeting_summary"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingMeetingSummary} resolves to. */
export type GetMeetingMeetingSummaryResponse =
	paths["/meetings/{meetingId}/meeting_summary"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/meeting_summary`
 *
 * Get a meeting or webinar summary
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_summary:read` `meeting_summary:read:admin` `meeting:read:summary` `meeting:read:summary:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingMeetingSummary(
	meetingId: GetMeetingMeetingSummaryWirePath["meetingId"],
): Operation<GetMeetingMeetingSummaryResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/meeting_summary`,
	};
}

type DeleteMeetingMeetingSummaryWirePath = NonNullable<paths["/meetings/{meetingId}/meeting_summary"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /meetings/{meetingId}/meeting_summary`
 *
 * Delete a meeting or webinar summary
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_summary:write` `meeting_summary:write:admin` `meeting:delete:summary` `meeting:delete:summary:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingMeetingSummary(
	meetingId: DeleteMeetingMeetingSummaryWirePath["meetingId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/meeting_summary`,
		decode: async () => undefined,
	};
}

type CreateMeetingOpenAppWirePath = NonNullable<paths["/meetings/{meetingId}/open_apps"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createMeetingOpenApp}. */
export type CreateMeetingOpenAppBody = NonNullable<paths["/meetings/{meetingId}/open_apps"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingOpenApp} resolves to. */
export type CreateMeetingOpenAppResponse =
	paths["/meetings/{meetingId}/open_apps"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/open_apps`
 *
 * Add a meeting app
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:write:open_app` `meeting:write:open_app:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingOpenApp(
	meetingId: CreateMeetingOpenAppWirePath["meetingId"],
	input: CreateMeetingOpenAppBody,
): Operation<CreateMeetingOpenAppResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/open_apps`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type DeleteMeetingOpenAppsWirePath = NonNullable<paths["/meetings/{meetingId}/open_apps"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /meetings/{meetingId}/open_apps`
 *
 * Delete a meeting app
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:delete:open_app` `meeting:delete:open_app:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingOpenApps(
	meetingId: DeleteMeetingOpenAppsWirePath["meetingId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/open_apps`,
		decode: async () => undefined,
	};
}

type ListMeetingPollsWirePath = NonNullable<paths["/meetings/{meetingId}/polls"]["get"]["parameters"]["path"]>;

type ListMeetingPollsWireQuery = NonNullable<paths["/meetings/{meetingId}/polls"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listMeetingPolls}. */
export interface ListMeetingPollsQuery {
	/**
	 * Whether to query for polls with the **Anonymous** option enabled: 
	 * * `true` &mdash; Query for polls with the **Anonymous** option enabled. 
	 * * `false` &mdash; Do not query for polls with the **Anonymous** option enabled.
	 */
	readonly anonymous?: Sendable<ListMeetingPollsWireQuery["anonymous"]>;
}

/** What {@link listMeetingPolls} resolves to. */
export type ListMeetingPollsResponse =
	paths["/meetings/{meetingId}/polls"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/polls`
 *
 * List meeting polls
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:list_polls` `meeting:read:list_polls:admin` and openapi_authorization: header `Authorization`
 */
export function listMeetingPolls(
	meetingId: ListMeetingPollsWirePath["meetingId"],
	query: ListMeetingPollsQuery = {},
): Operation<ListMeetingPollsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/polls`,
		query: {
			anonymous: query.anonymous,
		},
	};
}

type CreateMeetingPollWirePath = NonNullable<paths["/meetings/{meetingId}/polls"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createMeetingPoll}. */
export type CreateMeetingPollBody = NonNullable<paths["/meetings/{meetingId}/polls"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingPoll} resolves to. */
export type CreateMeetingPollResponse =
	paths["/meetings/{meetingId}/polls"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/polls`
 *
 * Create a meeting poll
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:write:poll` `meeting:write:poll:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingPoll(
	meetingId: CreateMeetingPollWirePath["meetingId"],
	input: CreateMeetingPollBody,
): Operation<CreateMeetingPollResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/polls`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetMeetingPollWirePath = NonNullable<paths["/meetings/{meetingId}/polls/{pollId}"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingPoll} resolves to. */
export type GetMeetingPollResponse =
	paths["/meetings/{meetingId}/polls/{pollId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/polls/{pollId}`
 *
 * Get a meeting poll
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:poll` `meeting:read:poll:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingPoll(
	meetingId: GetMeetingPollWirePath["meetingId"],
	pollId: GetMeetingPollWirePath["pollId"],
): Operation<GetMeetingPollResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/polls/${encodeURIComponent(String(pollId))}`,
	};
}

type ReplaceMeetingPollWirePath = NonNullable<paths["/meetings/{meetingId}/polls/{pollId}"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link replaceMeetingPoll}. */
export type ReplaceMeetingPollBody = NonNullable<paths["/meetings/{meetingId}/polls/{pollId}"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /meetings/{meetingId}/polls/{pollId}`
 *
 * Update a meeting poll
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:update:poll` `meeting:update:poll:admin` and openapi_authorization: header `Authorization`
 */
export function replaceMeetingPoll(
	meetingId: ReplaceMeetingPollWirePath["meetingId"],
	pollId: ReplaceMeetingPollWirePath["pollId"],
	input: ReplaceMeetingPollBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/polls/${encodeURIComponent(String(pollId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type DeleteMeetingPollWirePath = NonNullable<paths["/meetings/{meetingId}/polls/{pollId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /meetings/{meetingId}/polls/{pollId}`
 *
 * Delete a meeting poll
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:delete:poll` `meeting:delete:poll:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingPoll(
	meetingId: DeleteMeetingPollWirePath["meetingId"],
	pollId: DeleteMeetingPollWirePath["pollId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/polls/${encodeURIComponent(String(pollId))}`,
		decode: async () => undefined,
	};
}

type ListMeetingRecordingsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings"]["get"]["parameters"]["path"]>;

type ListMeetingRecordingsWireQuery = NonNullable<paths["/meetings/{meetingId}/recordings"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listMeetingRecordings}. */
export interface ListMeetingRecordingsQuery {
	/** Include fields in the response. Currently, only accepts `download_access_token` to get this token field and value for downloading the meeting's recordings. The `download_access_token` requires **View the recording content** enabled for the role authorizing the account. Use the format `include_fields=download_access_token`. */
	readonly includeFields?: Sendable<ListMeetingRecordingsWireQuery["include_fields"]>;

	/** The `download_access_token` Time to Live (TTL) value. This parameter is only valid if the `include_fields` query parameter contains the value `download_access_token`. */
	readonly ttl?: Sendable<ListMeetingRecordingsWireQuery["ttl"]>;
}

/** What {@link listMeetingRecordings} resolves to. */
export type ListMeetingRecordingsResponse =
	paths["/meetings/{meetingId}/recordings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/recordings`
 *
 * Get meeting recordings
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read` `phone_recording:read:admin` `cloud_recording:read:list_recording_files:admin` `cloud_recording:read:list_recording_files` `cloud_recording:read:list_recording_files:master` and openapi_authorization: header `Authorization`
 */
export function listMeetingRecordings(
	meetingId: ListMeetingRecordingsWirePath["meetingId"],
	query: ListMeetingRecordingsQuery = {},
): Operation<ListMeetingRecordingsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings`,
		query: {
			include_fields: query.includeFields,
			ttl: query.ttl,
		},
	};
}

type DeleteMeetingRecordingsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings"]["delete"]["parameters"]["path"]>;

type DeleteMeetingRecordingsWireQuery = NonNullable<paths["/meetings/{meetingId}/recordings"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteMeetingRecordings}. */
export interface DeleteMeetingRecordingsQuery {
	/**
	 * The recording delete actions.  
	 *  `trash` - Move recording to trash.  
	 *  `delete` - Delete recording permanently.
	 */
	readonly action?: Sendable<DeleteMeetingRecordingsWireQuery["action"]>;
}

/**
 * `DELETE /meetings/{meetingId}/recordings`
 *
 * Delete meeting or webinar recordings
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:delete:meeting_recording` `cloud_recording:delete:meeting_recording:admin` `cloud_recording:delete:meeting_recording:master` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingRecordings(
	meetingId: DeleteMeetingRecordingsWirePath["meetingId"],
	query: DeleteMeetingRecordingsQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings`,
		query: {
			action: query.action,
		},
		decode: async () => undefined,
	};
}

type ListMeetingRecordingAnalyticsDetailsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/analytics_details"]["get"]["parameters"]["path"]>;

type ListMeetingRecordingAnalyticsDetailsWireQuery = NonNullable<paths["/meetings/{meetingId}/recordings/analytics_details"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listMeetingRecordingAnalyticsDetails}. */
export interface ListMeetingRecordingAnalyticsDetailsQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListMeetingRecordingAnalyticsDetailsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListMeetingRecordingAnalyticsDetailsWireQuery["next_page_token"]>;

	/** The start date for the monthly range to query. The maximum range can be a month. If you do not provide this value, this defaults to the current date. */
	readonly from?: Sendable<ListMeetingRecordingAnalyticsDetailsWireQuery["from"]>;

	/** The end date for the monthly range to query. The maximum range can be a month. */
	readonly to?: Sendable<ListMeetingRecordingAnalyticsDetailsWireQuery["to"]>;

	/**
	 * The type of analytics details: 
	 * * `by_view` &mdash; by_view. 
	 * * `by_download` &mdash; by_download.
	 */
	readonly type?: Sendable<ListMeetingRecordingAnalyticsDetailsWireQuery["type"]>;
}

/** What {@link listMeetingRecordingAnalyticsDetails} resolves to. */
export type ListMeetingRecordingAnalyticsDetailsResponse =
	paths["/meetings/{meetingId}/recordings/analytics_details"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/recordings/analytics_details`
 *
 * Get a meeting or webinar recording's analytics details
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `cloud_recording:read:recording_analytics_details` `cloud_recording:read:recording_analytics_details:master` `cloud_recording:read:recording_analytics_details:admin` and openapi_authorization: header `Authorization`
 */
export function listMeetingRecordingAnalyticsDetails(
	meetingId: ListMeetingRecordingAnalyticsDetailsWirePath["meetingId"],
	query: ListMeetingRecordingAnalyticsDetailsQuery = {},
): Operation<ListMeetingRecordingAnalyticsDetailsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/analytics_details`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			from: query.from,
			to: query.to,
			type: query.type,
		},
	};
}

type GetMeetingRecordingAnalyticsSummaryWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/analytics_summary"]["get"]["parameters"]["path"]>;

type GetMeetingRecordingAnalyticsSummaryWireQuery = NonNullable<paths["/meetings/{meetingId}/recordings/analytics_summary"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getMeetingRecordingAnalyticsSummary}. */
export interface GetMeetingRecordingAnalyticsSummaryQuery {
	/** The start date for the monthly range to query. The maximum range can be a month. If you do not provide this value, this defaults to the current date. */
	readonly from?: Sendable<GetMeetingRecordingAnalyticsSummaryWireQuery["from"]>;

	/** The end date for the monthly range to query. The maximum range can be a month. */
	readonly to?: Sendable<GetMeetingRecordingAnalyticsSummaryWireQuery["to"]>;
}

/** What {@link getMeetingRecordingAnalyticsSummary} resolves to. */
export type GetMeetingRecordingAnalyticsSummaryResponse =
	paths["/meetings/{meetingId}/recordings/analytics_summary"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/recordings/analytics_summary`
 *
 * Get a meeting or webinar recording's analytics summary
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `cloud_recording:read:recording_analytics_summary` `cloud_recording:read:recording_analytics_summary:master` `cloud_recording:read:recording_analytics_summary:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingRecordingAnalyticsSummary(
	meetingId: GetMeetingRecordingAnalyticsSummaryWirePath["meetingId"],
	query: GetMeetingRecordingAnalyticsSummaryQuery = {},
): Operation<GetMeetingRecordingAnalyticsSummaryResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/analytics_summary`,
		query: {
			from: query.from,
			to: query.to,
		},
	};
}

type ListMeetingRecordingRegistrantsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/registrants"]["get"]["parameters"]["path"]>;

type ListMeetingRecordingRegistrantsWireQuery = NonNullable<paths["/meetings/{meetingId}/recordings/registrants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listMeetingRecordingRegistrants}. */
export interface ListMeetingRecordingRegistrantsQuery {
	/**
	 * Query by the registrant's status. 
	 * * `pending` - The registration is pending. 
	 * * `approved` - The registrant is approved. 
	 * * `denied` - The registration is denied.
	 */
	readonly status?: Sendable<ListMeetingRecordingRegistrantsWireQuery["status"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListMeetingRecordingRegistrantsWireQuery["page_size"]>;

	/** **Deprecated.** We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination. */
	readonly pageNumber?: Sendable<ListMeetingRecordingRegistrantsWireQuery["page_number"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListMeetingRecordingRegistrantsWireQuery["next_page_token"]>;
}

/** What {@link listMeetingRecordingRegistrants} resolves to. */
export type ListMeetingRecordingRegistrantsResponse =
	paths["/meetings/{meetingId}/recordings/registrants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/recordings/registrants`
 *
 * List recording registrants
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read:admin` `recording:read` `cloud_recording:read:list_recording_registrants` `cloud_recording:read:list_recording_registrants:admin` `cloud_recording:read:list_recording_registrants:master` and openapi_authorization: header `Authorization`
 */
export function listMeetingRecordingRegistrants(
	meetingId: ListMeetingRecordingRegistrantsWirePath["meetingId"],
	query: ListMeetingRecordingRegistrantsQuery = {},
): Operation<ListMeetingRecordingRegistrantsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/registrants`,
		query: {
			status: query.status,
			page_size: query.pageSize,
			page_number: query.pageNumber,
			next_page_token: query.nextPageToken,
		},
	};
}

type CreateMeetingRecordingRegistrantWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/registrants"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createMeetingRecordingRegistrant}. */
export type CreateMeetingRecordingRegistrantBody = NonNullable<paths["/meetings/{meetingId}/recordings/registrants"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingRecordingRegistrant} resolves to. */
export type CreateMeetingRecordingRegistrantResponse =
	paths["/meetings/{meetingId}/recordings/registrants"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/recordings/registrants`
 *
 * Create a recording registrant
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:write:recording_registrant` `cloud_recording:write:recording_registrant:master` `cloud_recording:write:recording_registrant:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingRecordingRegistrant(
	meetingId: CreateMeetingRecordingRegistrantWirePath["meetingId"],
	input: CreateMeetingRecordingRegistrantBody,
): Operation<CreateMeetingRecordingRegistrantResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/registrants`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ListMeetingRecordingRegistrantQuestionsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/registrants/questions"]["get"]["parameters"]["path"]>;

/** What {@link listMeetingRecordingRegistrantQuestions} resolves to. */
export type ListMeetingRecordingRegistrantQuestionsResponse =
	paths["/meetings/{meetingId}/recordings/registrants/questions"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/recordings/registrants/questions`
 *
 * Get registration questions
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read:admin` `recording:read` `cloud_recording:read:registration_questions` `cloud_recording:read:registration_questions:master` `cloud_recording:read:registration_questions:admin` and openapi_authorization: header `Authorization`
 */
export function listMeetingRecordingRegistrantQuestions(
	meetingId: ListMeetingRecordingRegistrantQuestionsWirePath["meetingId"],
): Operation<ListMeetingRecordingRegistrantQuestionsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/registrants/questions`,
	};
}

type UpdateMeetingRecordingRegistrantQuestionsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/registrants/questions"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateMeetingRecordingRegistrantQuestions}. */
export type UpdateMeetingRecordingRegistrantQuestionsBody = NonNullable<paths["/meetings/{meetingId}/recordings/registrants/questions"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}/recordings/registrants/questions`
 *
 * Update registration questions
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:update:registration_questions:admin` `cloud_recording:update:registration_questions` `cloud_recording:update:registration_questions:master` and openapi_authorization: header `Authorization`
 */
export function updateMeetingRecordingRegistrantQuestions(
	meetingId: UpdateMeetingRecordingRegistrantQuestionsWirePath["meetingId"],
	patch: UpdateMeetingRecordingRegistrantQuestionsBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/registrants/questions`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type ReplaceMeetingRecordingRegistrantStatusWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/registrants/status"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link replaceMeetingRecordingRegistrantStatus}. */
export type ReplaceMeetingRecordingRegistrantStatusBody = NonNullable<paths["/meetings/{meetingId}/recordings/registrants/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /meetings/{meetingId}/recordings/registrants/status`
 *
 * Update a registrant's status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:update:registrant_status` `cloud_recording:update:registrant_status:master` `cloud_recording:update:registrant_status:admin` and openapi_authorization: header `Authorization`
 */
export function replaceMeetingRecordingRegistrantStatus(
	meetingId: ReplaceMeetingRecordingRegistrantStatusWirePath["meetingId"],
	input: ReplaceMeetingRecordingRegistrantStatusBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/registrants/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type ListMeetingRecordingSettingsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/settings"]["get"]["parameters"]["path"]>;

/** What {@link listMeetingRecordingSettings} resolves to. */
export type ListMeetingRecordingSettingsResponse =
	paths["/meetings/{meetingId}/recordings/settings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/recordings/settings`
 *
 * Get meeting recording settings
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read:admin` `recording:read` `cloud_recording:read:recording_settings` `cloud_recording:read:recording_settings:admin` `cloud_recording:read:recording_settings:master` and openapi_authorization: header `Authorization`
 */
export function listMeetingRecordingSettings(
	meetingId: ListMeetingRecordingSettingsWirePath["meetingId"],
): Operation<ListMeetingRecordingSettingsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/settings`,
	};
}

type UpdateMeetingRecordingSettingsWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/settings"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateMeetingRecordingSettings}. */
export type UpdateMeetingRecordingSettingsBody = NonNullable<paths["/meetings/{meetingId}/recordings/settings"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}/recordings/settings`
 *
 * Update meeting recording settings
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:update:recording_settings` `cloud_recording:update:recording_settings:master` `cloud_recording:update:recording_settings:admin` and openapi_authorization: header `Authorization`
 */
export function updateMeetingRecordingSettings(
	meetingId: UpdateMeetingRecordingSettingsWirePath["meetingId"],
	patch: UpdateMeetingRecordingSettingsBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/settings`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteMeetingRecordingWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/{recordingId}"]["delete"]["parameters"]["path"]>;

type DeleteMeetingRecordingWireQuery = NonNullable<paths["/meetings/{meetingId}/recordings/{recordingId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteMeetingRecording}. */
export interface DeleteMeetingRecordingQuery {
	/**
	 * The recording delete actions. 
	 *  `trash` - Move recording to trash.  
	 *  `delete` - Delete recording permanently.
	 */
	readonly action?: Sendable<DeleteMeetingRecordingWireQuery["action"]>;
}

/**
 * `DELETE /meetings/{meetingId}/recordings/{recordingId}`
 *
 * Delete a recording file for a meeting or webinar
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:delete:recording_file` `cloud_recording:delete:recording_file:admin` `cloud_recording:delete:recording_file:master` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingRecording(
	meetingId: DeleteMeetingRecordingWirePath["meetingId"],
	recordingId: DeleteMeetingRecordingWirePath["recordingId"],
	query: DeleteMeetingRecordingQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/${encodeURIComponent(String(recordingId))}`,
		query: {
			action: query.action,
		},
		decode: async () => undefined,
	};
}

type ReplaceMeetingRecordingStatusWirePath = NonNullable<paths["/meetings/{meetingId}/recordings/{recordingId}/status"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link replaceMeetingRecordingStatus}. */
export type ReplaceMeetingRecordingStatusBody = NonNullable<paths["/meetings/{meetingId}/recordings/{recordingId}/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /meetings/{meetingId}/recordings/{recordingId}/status`
 *
 * Recover a single recording
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:update:recover_single_recording` `cloud_recording:update:recover_single_recording:master` `cloud_recording:update:recover_single_recording:admin` and openapi_authorization: header `Authorization`
 */
export function replaceMeetingRecordingStatus(
	meetingId: ReplaceMeetingRecordingStatusWirePath["meetingId"],
	recordingId: ReplaceMeetingRecordingStatusWirePath["recordingId"],
	input: ReplaceMeetingRecordingStatusBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/recordings/${encodeURIComponent(String(recordingId))}/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type ListMeetingRegistrantsWirePath = NonNullable<paths["/meetings/{meetingId}/registrants"]["get"]["parameters"]["path"]>;

type ListMeetingRegistrantsWireQuery = NonNullable<paths["/meetings/{meetingId}/registrants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listMeetingRegistrants}. */
export interface ListMeetingRegistrantsQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<ListMeetingRegistrantsWireQuery["occurrence_id"]>;

	/**
	 * Query by the registrant's status. 
	 * * `pending` - The registration is pending. 
	 * * `approved` - The registrant is approved. 
	 * * `denied` - The registration is denied.
	 */
	readonly status?: Sendable<ListMeetingRegistrantsWireQuery["status"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListMeetingRegistrantsWireQuery["page_size"]>;

	/** **Deprecated.** We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination. */
	readonly pageNumber?: Sendable<ListMeetingRegistrantsWireQuery["page_number"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListMeetingRegistrantsWireQuery["next_page_token"]>;
}

/** What {@link listMeetingRegistrants} resolves to. */
export type ListMeetingRegistrantsResponse =
	paths["/meetings/{meetingId}/registrants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/registrants`
 *
 * List meeting registrants
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:list_registrants` `meeting:read:list_registrants:admin` and openapi_authorization: header `Authorization`
 */
export function listMeetingRegistrants(
	meetingId: ListMeetingRegistrantsWirePath["meetingId"],
	query: ListMeetingRegistrantsQuery = {},
): Operation<ListMeetingRegistrantsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants`,
		query: {
			occurrence_id: query.occurrenceId,
			status: query.status,
			page_size: query.pageSize,
			page_number: query.pageNumber,
			next_page_token: query.nextPageToken,
		},
	};
}

type CreateMeetingRegistrantWirePath = NonNullable<paths["/meetings/{meetingId}/registrants"]["post"]["parameters"]["path"]>;

type CreateMeetingRegistrantWireQuery = NonNullable<paths["/meetings/{meetingId}/registrants"]["post"]["parameters"]["query"]>;

/** Query accepted by {@link createMeetingRegistrant}. */
export interface CreateMeetingRegistrantQuery {
	/** A comma-separated list of meeting occurrence IDs. You can get this value with the [Get a meeting](/docs/api-reference/zoom-api/methods#operation/meeting) API. */
	readonly occurrenceIds?: Sendable<CreateMeetingRegistrantWireQuery["occurrence_ids"]>;
}

/** Body accepted by {@link createMeetingRegistrant}. */
export type CreateMeetingRegistrantBody = NonNullable<paths["/meetings/{meetingId}/registrants"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createMeetingRegistrant} resolves to. */
export type CreateMeetingRegistrantResponse =
	paths["/meetings/{meetingId}/registrants"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/registrants`
 *
 * Add a meeting registrant
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:write:registrant` `meeting:write:registrant:admin` and openapi_authorization: header `Authorization`
 */
export function createMeetingRegistrant(
	meetingId: CreateMeetingRegistrantWirePath["meetingId"],
	input: CreateMeetingRegistrantBody,
	query: CreateMeetingRegistrantQuery = {},
): Operation<CreateMeetingRegistrantResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants`,
		query: {
			occurrence_ids: query.occurrenceIds,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ListMeetingRegistrantQuestionsWirePath = NonNullable<paths["/meetings/{meetingId}/registrants/questions"]["get"]["parameters"]["path"]>;

/** What {@link listMeetingRegistrantQuestions} resolves to. */
export type ListMeetingRegistrantQuestionsResponse =
	paths["/meetings/{meetingId}/registrants/questions"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/registrants/questions`
 *
 * List registration questions 
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:list_registration_questions` `meeting:read:list_registration_questions:admin` and openapi_authorization: header `Authorization`
 */
export function listMeetingRegistrantQuestions(
	meetingId: ListMeetingRegistrantQuestionsWirePath["meetingId"],
): Operation<ListMeetingRegistrantQuestionsResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants/questions`,
	};
}

type UpdateMeetingRegistrantQuestionsWirePath = NonNullable<paths["/meetings/{meetingId}/registrants/questions"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateMeetingRegistrantQuestions}. */
export type UpdateMeetingRegistrantQuestionsBody = NonNullable<paths["/meetings/{meetingId}/registrants/questions"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}/registrants/questions`
 *
 * Update registration questions
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:update:registration_question` `meeting:update:registration_question:admin` and openapi_authorization: header `Authorization`
 */
export function updateMeetingRegistrantQuestions(
	meetingId: UpdateMeetingRegistrantQuestionsWirePath["meetingId"],
	patch: UpdateMeetingRegistrantQuestionsBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants/questions`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type ReplaceMeetingRegistrantStatusWirePath = NonNullable<paths["/meetings/{meetingId}/registrants/status"]["put"]["parameters"]["path"]>;

type ReplaceMeetingRegistrantStatusWireQuery = NonNullable<paths["/meetings/{meetingId}/registrants/status"]["put"]["parameters"]["query"]>;

/** Query accepted by {@link replaceMeetingRegistrantStatus}. */
export interface ReplaceMeetingRegistrantStatusQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<ReplaceMeetingRegistrantStatusWireQuery["occurrence_id"]>;
}

/** Body accepted by {@link replaceMeetingRegistrantStatus}. */
export type ReplaceMeetingRegistrantStatusBody = NonNullable<paths["/meetings/{meetingId}/registrants/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /meetings/{meetingId}/registrants/status`
 *
 * Update registrant's status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:update:registrant_status` `meeting:update:registrant_status:admin` and openapi_authorization: header `Authorization`
 */
export function replaceMeetingRegistrantStatus(
	meetingId: ReplaceMeetingRegistrantStatusWirePath["meetingId"],
	input: ReplaceMeetingRegistrantStatusBody,
	query: ReplaceMeetingRegistrantStatusQuery = {},
): Operation<void> {
	return {
		method: "PUT",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants/status`,
		query: {
			occurrence_id: query.occurrenceId,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type GetMeetingRegistrantWirePath = NonNullable<paths["/meetings/{meetingId}/registrants/{registrantId}"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingRegistrant} resolves to. */
export type GetMeetingRegistrantResponse =
	paths["/meetings/{meetingId}/registrants/{registrantId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/registrants/{registrantId}`
 *
 * Get a meeting registrant
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:registrant` `meeting:read:registrant:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingRegistrant(
	meetingId: GetMeetingRegistrantWirePath["meetingId"],
	registrantId: GetMeetingRegistrantWirePath["registrantId"],
): Operation<GetMeetingRegistrantResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants/${encodeURIComponent(String(registrantId))}`,
	};
}

type DeleteMeetingRegistrantWirePath = NonNullable<paths["/meetings/{meetingId}/registrants/{registrantId}"]["delete"]["parameters"]["path"]>;

type DeleteMeetingRegistrantWireQuery = NonNullable<paths["/meetings/{meetingId}/registrants/{registrantId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteMeetingRegistrant}. */
export interface DeleteMeetingRegistrantQuery {
	/** The meeting occurrence ID. */
	readonly occurrenceId?: Sendable<DeleteMeetingRegistrantWireQuery["occurrence_id"]>;
}

/**
 * `DELETE /meetings/{meetingId}/registrants/{registrantId}`
 *
 * Delete a meeting registrant
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:delete:registrant` `meeting:delete:registrant:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingRegistrant(
	meetingId: DeleteMeetingRegistrantWirePath["meetingId"],
	registrantId: DeleteMeetingRegistrantWirePath["registrantId"],
	query: DeleteMeetingRegistrantQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/registrants/${encodeURIComponent(String(registrantId))}`,
		query: {
			occurrence_id: query.occurrenceId,
		},
		decode: async () => undefined,
	};
}

type SipDialingMeetingWirePath = NonNullable<paths["/meetings/{meetingId}/sip_dialing"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link sipDialingMeeting}. */
export type SipDialingMeetingBody = NonNullable<paths["/meetings/{meetingId}/sip_dialing"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link sipDialingMeeting} resolves to. */
export type SipDialingMeetingResponse =
	paths["/meetings/{meetingId}/sip_dialing"]["post"]["responses"][200]["content"]["application/json"];

/**
 * `POST /meetings/{meetingId}/sip_dialing`
 *
 * Get a meeting SIP URI with passcode
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:sip_dialing` `meeting:write:admin:sip_dialing` `meeting:write:sip_dialing` `meeting:write:sip_dialing:admin` and openapi_authorization: header `Authorization`
 */
export function sipDialingMeeting(
	meetingId: SipDialingMeetingWirePath["meetingId"],
	input: SipDialingMeetingBody,
): Operation<SipDialingMeetingResponse> {
	return {
		method: "POST",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/sip_dialing`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ReplaceMeetingStatusWirePath = NonNullable<paths["/meetings/{meetingId}/status"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link replaceMeetingStatus}. */
export type ReplaceMeetingStatusBody = NonNullable<paths["/meetings/{meetingId}/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /meetings/{meetingId}/status`
 *
 * Update meeting status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:update:status` `meeting:update:status:admin` and openapi_authorization: header `Authorization`
 */
export function replaceMeetingStatus(
	meetingId: ReplaceMeetingStatusWirePath["meetingId"],
	input: ReplaceMeetingStatusBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type GetMeetingSurveyWirePath = NonNullable<paths["/meetings/{meetingId}/survey"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingSurvey} resolves to. */
export type GetMeetingSurveyResponse =
	paths["/meetings/{meetingId}/survey"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/survey`
 *
 * Get a meeting survey
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:survey` `meeting:read:survey:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingSurvey(
	meetingId: GetMeetingSurveyWirePath["meetingId"],
): Operation<GetMeetingSurveyResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/survey`,
	};
}

type UpdateMeetingSurveyWirePath = NonNullable<paths["/meetings/{meetingId}/survey"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateMeetingSurvey}. */
export type UpdateMeetingSurveyBody = NonNullable<paths["/meetings/{meetingId}/survey"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /meetings/{meetingId}/survey`
 *
 * Update a meeting survey
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:update:survey` `meeting:update:survey:admin` and openapi_authorization: header `Authorization`
 */
export function updateMeetingSurvey(
	meetingId: UpdateMeetingSurveyWirePath["meetingId"],
	patch: UpdateMeetingSurveyBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/survey`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteMeetingSurveyWirePath = NonNullable<paths["/meetings/{meetingId}/survey"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /meetings/{meetingId}/survey`
 *
 * Delete a meeting survey
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write` `meeting:write:admin` `meeting:delete:survey` `meeting:delete:survey:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingSurvey(
	meetingId: DeleteMeetingSurveyWirePath["meetingId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/survey`,
		decode: async () => undefined,
	};
}

type GetMeetingTokenWirePath = NonNullable<paths["/meetings/{meetingId}/token"]["get"]["parameters"]["path"]>;

type GetMeetingTokenWireQuery = NonNullable<paths["/meetings/{meetingId}/token"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getMeetingToken}. */
export interface GetMeetingTokenQuery {
	/**
	 * The meeting token type. 
	 * * `closed_caption_token` - The third-party closed caption API token. 
	 *
	 * This defaults to `closed_caption_token`.
	 */
	readonly type?: Sendable<GetMeetingTokenWireQuery["type"]>;
}

/** What {@link getMeetingToken} resolves to. */
export type GetMeetingTokenResponse =
	paths["/meetings/{meetingId}/token"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/token`
 *
 * Get meeting's token
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:token` `meeting:read:token:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingToken(
	meetingId: GetMeetingTokenWirePath["meetingId"],
	query: GetMeetingTokenQuery = {},
): Operation<GetMeetingTokenResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/token`,
		query: {
			type: query.type,
		},
	};
}

type GetMeetingTranscriptWirePath = NonNullable<paths["/meetings/{meetingId}/transcript"]["get"]["parameters"]["path"]>;

/** What {@link getMeetingTranscript} resolves to. */
export type GetMeetingTranscriptResponse =
	paths["/meetings/{meetingId}/transcript"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /meetings/{meetingId}/transcript`
 *
 * Get a meeting transcript
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read` `recording:write` `recording:read:admin` `recording:write:admin` `cloud_recording:read:meeting_transcript` `cloud_recording:read:meeting_transcript:admin` and openapi_authorization: header `Authorization`
 */
export function getMeetingTranscript(
	meetingId: GetMeetingTranscriptWirePath["meetingId"],
): Operation<GetMeetingTranscriptResponse> {
	return {
		method: "GET",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/transcript`,
	};
}

type DeleteMeetingTranscriptWirePath = NonNullable<paths["/meetings/{meetingId}/transcript"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /meetings/{meetingId}/transcript`
 *
 * Delete a meeting or webinar transcript
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write` `recording:write:admin` `cloud_recording:delete:meeting_transcript` `cloud_recording:delete:meeting_transcript:admin` and openapi_authorization: header `Authorization`
 */
export function deleteMeetingTranscript(
	meetingId: DeleteMeetingTranscriptWirePath["meetingId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/meetings/${encodeURIComponent(String(meetingId))}/transcript`,
		decode: async () => undefined,
	};
}

type RecoverMeetingRecordingsWirePath = NonNullable<paths["/meetings/{meetingUUID}/recordings/status"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link recoverMeetingRecordings}. */
export type RecoverMeetingRecordingsBody = NonNullable<paths["/meetings/{meetingUUID}/recordings/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /meetings/{meetingUUID}/recordings/status`
 *
 * Recover meeting recordings
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `recording:write` `cloud_recording:update:recover_meeting_recordings` `cloud_recording:update:recover_meeting_recordings:master` `cloud_recording:update:recover_meeting_recordings:admin` and openapi_authorization: header `Authorization`
 */
export function recoverMeetingRecordings(
	meetingUuid: RecoverMeetingRecordingsWirePath["meetingUUID"],
	input: RecoverMeetingRecordingsBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/meetings/${encodeURIComponent(String(meetingUuid))}/recordings/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}
