// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListPastWebinarAbsenteesWirePath = NonNullable<paths["/past_webinars/{webinarId}/absentees"]["get"]["parameters"]["path"]>;

type ListPastWebinarAbsenteesWireQuery = NonNullable<paths["/past_webinars/{webinarId}/absentees"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listPastWebinarAbsentees}. */
export interface ListPastWebinarAbsenteesQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<ListPastWebinarAbsenteesWireQuery["occurrence_id"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListPastWebinarAbsenteesWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListPastWebinarAbsenteesWireQuery["next_page_token"]>;
}

/** What {@link listPastWebinarAbsentees} resolves to. */
export type ListPastWebinarAbsenteesResponse =
	paths["/past_webinars/{webinarId}/absentees"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_webinars/{webinarId}/absentees`
 *
 * Get webinar absentees
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_absentees` `webinar:read:list_absentees:admin` and openapi_authorization: header `Authorization`
 */
export function listPastWebinarAbsentees(
	webinarId: ListPastWebinarAbsenteesWirePath["webinarId"],
	query: ListPastWebinarAbsenteesQuery = {},
): Operation<ListPastWebinarAbsenteesResponse> {
	return {
		method: "GET",
		path: `/past_webinars/${encodeURIComponent(String(webinarId))}/absentees`,
		query: {
			occurrence_id: query.occurrenceId,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

type ListPastWebinarInstancesWirePath = NonNullable<paths["/past_webinars/{webinarId}/instances"]["get"]["parameters"]["path"]>;

/** What {@link listPastWebinarInstances} resolves to. */
export type ListPastWebinarInstancesResponse =
	paths["/past_webinars/{webinarId}/instances"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_webinars/{webinarId}/instances`
 *
 * List past webinar instances
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_past_instances` `webinar:read:list_past_instances:admin` and openapi_authorization: header `Authorization`
 */
export function listPastWebinarInstances(
	webinarId: ListPastWebinarInstancesWirePath["webinarId"],
): Operation<ListPastWebinarInstancesResponse> {
	return {
		method: "GET",
		path: `/past_webinars/${encodeURIComponent(String(webinarId))}/instances`,
	};
}

type ListPastWebinarParticipantsWirePath = NonNullable<paths["/past_webinars/{webinarId}/participants"]["get"]["parameters"]["path"]>;

type ListPastWebinarParticipantsWireQuery = NonNullable<paths["/past_webinars/{webinarId}/participants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listPastWebinarParticipants}. */
export interface ListPastWebinarParticipantsQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListPastWebinarParticipantsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListPastWebinarParticipantsWireQuery["next_page_token"]>;
}

/** What {@link listPastWebinarParticipants} resolves to. */
export type ListPastWebinarParticipantsResponse =
	paths["/past_webinars/{webinarId}/participants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_webinars/{webinarId}/participants`
 *
 * List webinar participants
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_past_participants:admin` `webinar:read:list_past_participants` and openapi_authorization: header `Authorization`
 */
export function listPastWebinarParticipants(
	webinarId: ListPastWebinarParticipantsWirePath["webinarId"],
	query: ListPastWebinarParticipantsQuery = {},
): Operation<ListPastWebinarParticipantsResponse> {
	return {
		method: "GET",
		path: `/past_webinars/${encodeURIComponent(String(webinarId))}/participants`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

type ListPastWebinarPollsWirePath = NonNullable<paths["/past_webinars/{webinarId}/polls"]["get"]["parameters"]["path"]>;

/** What {@link listPastWebinarPolls} resolves to. */
export type ListPastWebinarPollsResponse =
	paths["/past_webinars/{webinarId}/polls"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_webinars/{webinarId}/polls`
 *
 * List past webinar poll results
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_past_polls` `webinar:read:list_past_polls:admin` and openapi_authorization: header `Authorization`
 */
export function listPastWebinarPolls(
	webinarId: ListPastWebinarPollsWirePath["webinarId"],
): Operation<ListPastWebinarPollsResponse> {
	return {
		method: "GET",
		path: `/past_webinars/${encodeURIComponent(String(webinarId))}/polls`,
	};
}

type GetPastWebinarQaWirePath = NonNullable<paths["/past_webinars/{webinarId}/qa"]["get"]["parameters"]["path"]>;

/** What {@link getPastWebinarQa} resolves to. */
export type GetPastWebinarQaResponse =
	paths["/past_webinars/{webinarId}/qa"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_webinars/{webinarId}/qa`
 *
 * List Q&As of a past webinar
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:past_qa` `webinar:read:past_qa:admin` and openapi_authorization: header `Authorization`
 */
export function getPastWebinarQa(
	webinarId: GetPastWebinarQaWirePath["webinarId"],
): Operation<GetPastWebinarQaResponse> {
	return {
		method: "GET",
		path: `/past_webinars/${encodeURIComponent(String(webinarId))}/qa`,
	};
}
