// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type GetPastMeetingWirePath = NonNullable<paths["/past_meetings/{meetingId}"]["get"]["parameters"]["path"]>;

/** What {@link getPastMeeting} resolves to. */
export type GetPastMeetingResponse =
	paths["/past_meetings/{meetingId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_meetings/{meetingId}`
 *
 * Get past meeting details
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:past_meeting` `meeting:read:past_meeting:admin` and openapi_authorization: header `Authorization`
 */
export function getPastMeeting(
	meetingId: GetPastMeetingWirePath["meetingId"],
): Operation<GetPastMeetingResponse> {
	return {
		method: "GET",
		path: `/past_meetings/${encodeURIComponent(String(meetingId))}`,
	};
}

type ListPastMeetingInstancesWirePath = NonNullable<paths["/past_meetings/{meetingId}/instances"]["get"]["parameters"]["path"]>;

type ListPastMeetingInstancesWireQuery = NonNullable<paths["/past_meetings/{meetingId}/instances"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listPastMeetingInstances}. */
export interface ListPastMeetingInstancesQuery {
	/** Start date in UTC, in yyyy-MM-dd format. This parameter only takes effect when used together with to. For best performance, we recommend querying within a one-month range. */
	readonly from?: Sendable<ListPastMeetingInstancesWireQuery["from"]>;

	/** End date in UTC, in yyyy-MM-dd format. This parameter only takes effect when used together with from. */
	readonly to?: Sendable<ListPastMeetingInstancesWireQuery["to"]>;
}

/** What {@link listPastMeetingInstances} resolves to. */
export type ListPastMeetingInstancesResponse =
	paths["/past_meetings/{meetingId}/instances"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_meetings/{meetingId}/instances`
 *
 * List past meeting instances
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:list_past_instances` `meeting:read:list_past_instances:admin` and openapi_authorization: header `Authorization`
 */
export function listPastMeetingInstances(
	meetingId: ListPastMeetingInstancesWirePath["meetingId"],
	query: ListPastMeetingInstancesQuery = {},
): Operation<ListPastMeetingInstancesResponse> {
	return {
		method: "GET",
		path: `/past_meetings/${encodeURIComponent(String(meetingId))}/instances`,
		query: {
			from: query.from,
			to: query.to,
		},
	};
}

type ListPastMeetingParticipantsWirePath = NonNullable<paths["/past_meetings/{meetingId}/participants"]["get"]["parameters"]["path"]>;

type ListPastMeetingParticipantsWireQuery = NonNullable<paths["/past_meetings/{meetingId}/participants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listPastMeetingParticipants}. */
export interface ListPastMeetingParticipantsQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListPastMeetingParticipantsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListPastMeetingParticipantsWireQuery["next_page_token"]>;
}

/** What {@link listPastMeetingParticipants} resolves to. */
export type ListPastMeetingParticipantsResponse =
	paths["/past_meetings/{meetingId}/participants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_meetings/{meetingId}/participants`
 *
 * Get past meeting participants
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:list_past_participants` `meeting:read:list_past_participants:admin` and openapi_authorization: header `Authorization`
 */
export function listPastMeetingParticipants(
	meetingId: ListPastMeetingParticipantsWirePath["meetingId"],
	query: ListPastMeetingParticipantsQuery = {},
): Operation<ListPastMeetingParticipantsResponse> {
	return {
		method: "GET",
		path: `/past_meetings/${encodeURIComponent(String(meetingId))}/participants`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

type ListPastMeetingPollsWirePath = NonNullable<paths["/past_meetings/{meetingId}/polls"]["get"]["parameters"]["path"]>;

/** What {@link listPastMeetingPolls} resolves to. */
export type ListPastMeetingPollsResponse =
	paths["/past_meetings/{meetingId}/polls"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_meetings/{meetingId}/polls`
 *
 * List past meeting's poll results
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:list_poll_results` `meeting:read:list_poll_results:admin` and openapi_authorization: header `Authorization`
 */
export function listPastMeetingPolls(
	meetingId: ListPastMeetingPollsWirePath["meetingId"],
): Operation<ListPastMeetingPollsResponse> {
	return {
		method: "GET",
		path: `/past_meetings/${encodeURIComponent(String(meetingId))}/polls`,
	};
}

type GetPastMeetingQaWirePath = NonNullable<paths["/past_meetings/{meetingId}/qa"]["get"]["parameters"]["path"]>;

/** What {@link getPastMeetingQa} resolves to. */
export type GetPastMeetingQaResponse =
	paths["/past_meetings/{meetingId}/qa"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_meetings/{meetingId}/qa`
 *
 * List past meetings' Q&A
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:past_qa` `meeting:read:past_qa:admin` and openapi_authorization: header `Authorization`
 */
export function getPastMeetingQa(
	meetingId: GetPastMeetingQaWirePath["meetingId"],
): Operation<GetPastMeetingQaResponse> {
	return {
		method: "GET",
		path: `/past_meetings/${encodeURIComponent(String(meetingId))}/qa`,
	};
}

type ListPastMeetingArchiveFilesWirePath = NonNullable<paths["/past_meetings/{meetingUUID}/archive_files"]["get"]["parameters"]["path"]>;

/** What {@link listPastMeetingArchiveFiles} resolves to. */
export type ListPastMeetingArchiveFilesResponse =
	paths["/past_meetings/{meetingUUID}/archive_files"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /past_meetings/{meetingUUID}/archive_files`
 *
 * Get a meeting's archived files
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read` `archiving:read:archived_files:admin` `archiving:read:archived_files` and openapi_authorization: header `Authorization`
 */
export function listPastMeetingArchiveFiles(
	meetingUuid: ListPastMeetingArchiveFilesWirePath["meetingUUID"],
): Operation<ListPastMeetingArchiveFilesResponse> {
	return {
		method: "GET",
		path: `/past_meetings/${encodeURIComponent(String(meetingUuid))}/archive_files`,
	};
}

type DeletePastMeetingArchiveFilesWirePath = NonNullable<paths["/past_meetings/{meetingUUID}/archive_files"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /past_meetings/{meetingUUID}/archive_files`
 *
 * Delete a meeting's archived files
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:write:admin` `archiving:delete:archived_files:admin` and openapi_authorization: header `Authorization`
 */
export function deletePastMeetingArchiveFiles(
	meetingUuid: DeletePastMeetingArchiveFilesWirePath["meetingUUID"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/past_meetings/${encodeURIComponent(String(meetingUuid))}/archive_files`,
		decode: async () => undefined,
	};
}
