// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListReportActivitiesWireQuery = NonNullable<paths["/report/activities"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportActivities}. */
export interface ListReportActivitiesQuery {
	/** Start date for which you would like to view the activity logs report. Using the `from` and `to` parameters, specify a monthly date range for the report as the API only provides one month worth of data in one request. The specified date range should fall within the last six months. */
	readonly from?: Sendable<ListReportActivitiesWireQuery["from"]>;

	/** End date up to which you would like to view the activity logs report. */
	readonly to?: Sendable<ListReportActivitiesWireQuery["to"]>;

	/** The number of records to be returned within a single API call */
	readonly pageSize?: Sendable<ListReportActivitiesWireQuery["page_size"]>;

	/** Next page token is used to paginate through large result sets */
	readonly nextPageToken?: Sendable<ListReportActivitiesWireQuery["next_page_token"]>;
}

/** What {@link listReportActivities} resolves to. */
export type ListReportActivitiesResponse =
	paths["/report/activities"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/activities`
 *
 * Get sign In / sign out activity report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:user_activities:admin` and openapi_authorization: header `Authorization`
 */
export function listReportActivities(
	query: ListReportActivitiesQuery = {},
): Operation<ListReportActivitiesResponse> {
	return {
		method: "GET",
		path: "/report/activities",
		query: {
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

/** What {@link getReportBilling} resolves to. */
export type GetReportBillingResponse =
	paths["/report/billing"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/billing`
 *
 * Get billing reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:billing:admin` and openapi_authorization: header `Authorization`
 */
export function getReportBilling(): Operation<GetReportBillingResponse> {
	return {
		method: "GET",
		path: "/report/billing",
	};
}

type ListReportBillingInvoicesWireQuery = NonNullable<paths["/report/billing/invoices"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportBillingInvoices}. */
export interface ListReportBillingInvoicesQuery {
	/**
	 * The billing report's unique identifier. Retrieve this ID from the response of **Get Billing Reports** API request. 
	 *
	 *
	 */
	readonly billingId: Sendable<ListReportBillingInvoicesWireQuery["billing_id"]>;
}

/** What {@link listReportBillingInvoices} resolves to. */
export type ListReportBillingInvoicesResponse =
	paths["/report/billing/invoices"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/billing/invoices`
 *
 * Get billing invoice reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:billing_invoice:admin` and openapi_authorization: header `Authorization`
 */
export function listReportBillingInvoices(
	query: ListReportBillingInvoicesQuery,
): Operation<ListReportBillingInvoicesResponse> {
	return {
		method: "GET",
		path: "/report/billing/invoices",
		query: {
			billing_id: query.billingId,
		},
	};
}

type GetReportCloudRecordingWireQuery = NonNullable<paths["/report/cloud_recording"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getReportCloudRecording}. */
export interface GetReportCloudRecordingQuery {
	/** Start date in 'yyyy-mm-dd' format. The date range defined by the &quot;from&quot; and &quot;to&quot; parameters should only be one month as the report includes only one month worth of data at once. */
	readonly from: Sendable<GetReportCloudRecordingWireQuery["from"]>;

	/** End date. */
	readonly to: Sendable<GetReportCloudRecordingWireQuery["to"]>;

	/**
	 * The group ID. To get a group ID, use the [**List groups**](/api-reference/zoom-api/methods#operation/groups) API. 
	 *
	 *  **Note:** The API response will only contain users who are members of the queried group ID.
	 */
	readonly groupId?: Sendable<GetReportCloudRecordingWireQuery["group_id"]>;
}

/** What {@link getReportCloudRecording} resolves to. */
export type GetReportCloudRecordingResponse =
	paths["/report/cloud_recording"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/cloud_recording`
 *
 * Get cloud recording usage report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` and openapi_authorization: header `Authorization`
 */
export function getReportCloudRecording(
	query: GetReportCloudRecordingQuery,
): Operation<GetReportCloudRecordingResponse> {
	return {
		method: "GET",
		path: "/report/cloud_recording",
		query: {
			from: query.from,
			to: query.to,
			group_id: query.groupId,
		},
	};
}

type GetReportDailyWireQuery = NonNullable<paths["/report/daily"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getReportDaily}. */
export interface GetReportDailyQuery {
	/** Year for this report */
	readonly year?: Sendable<GetReportDailyWireQuery["year"]>;

	/** Month for this report */
	readonly month?: Sendable<GetReportDailyWireQuery["month"]>;

	/**
	 * The group ID. To get a group ID, use the [**List groups**](/docs/api/users/#tag/groups/GET/groups) API. 
	 *
	 *  **Note:** The API response will only contain users who are members of the queried group ID.
	 */
	readonly groupId?: Sendable<GetReportDailyWireQuery["group_id"]>;
}

/** What {@link getReportDaily} resolves to. */
export type GetReportDailyResponse =
	paths["/report/daily"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/daily`
 *
 * Get daily usage report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` and openapi_authorization: header `Authorization`
 */
export function getReportDaily(
	query: GetReportDailyQuery = {},
): Operation<GetReportDailyResponse> {
	return {
		method: "GET",
		path: "/report/daily",
		query: {
			year: query.year,
			month: query.month,
			group_id: query.groupId,
		},
	};
}

type GetReportDisclaimerWireQuery = NonNullable<paths["/report/disclaimer"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getReportDisclaimer}. */
export interface GetReportDisclaimerQuery {
	/** The start date in `yyyy-MM-dd` format. The date range defined by the `from` and `to` parameters should only be one month, as the report includes only one month's worth of data at once. It is the date range in which the disclaimer was generated. */
	readonly from: Sendable<GetReportDisclaimerWireQuery["from"]>;

	/** The end date in `yyyy-MM-dd` format. */
	readonly to: Sendable<GetReportDisclaimerWireQuery["to"]>;

	/** The user email or meeting number */
	readonly searchValue?: Sendable<GetReportDisclaimerWireQuery["search_value"]>;

	/** The disclaimer type. */
	readonly disclaimerType?: Sendable<GetReportDisclaimerWireQuery["disclaimer_type"]>;

	/** The user's group ID. */
	readonly groupId?: Sendable<GetReportDisclaimerWireQuery["group_id"]>;

	/** The number of records returned in a single API call. */
	readonly pageSize?: Sendable<GetReportDisclaimerWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<GetReportDisclaimerWireQuery["next_page_token"]>;
}

/** What {@link getReportDisclaimer} resolves to. */
export type GetReportDisclaimerResponse =
	paths["/report/disclaimer"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/disclaimer`
 *
 * Get disclaimer report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:disclaimer:admin` and openapi_authorization: header `Authorization`
 */
export function getReportDisclaimer(
	query: GetReportDisclaimerQuery,
): Operation<GetReportDisclaimerResponse> {
	return {
		method: "GET",
		path: "/report/disclaimer",
		query: {
			from: query.from,
			to: query.to,
			search_value: query.searchValue,
			disclaimer_type: query.disclaimerType,
			group_id: query.groupId,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

type ListReportHistoryMeetingsWireQuery = NonNullable<paths["/report/history_meetings"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportHistoryMeetings}. */
export interface ListReportHistoryMeetingsQuery {
	/** The start date in `yyyy-mm-dd` format. The date range defined by the `from` and `to` parameters should only be one month, as the report includes only one month worth of data at once. */
	readonly from: Sendable<ListReportHistoryMeetingsWireQuery["from"]>;

	/** The end date in `yyyy-mm-dd` format. */
	readonly to: Sendable<ListReportHistoryMeetingsWireQuery["to"]>;

	/**
	 * The type of date to query.
	 * * `start_time` - Query by meeting's start time. 
	 * * `end_time` - Query by meeting's end time. 
	 *
	 * This value defaults to `start_time`.
	 */
	readonly dateType?: Sendable<ListReportHistoryMeetingsWireQuery["date_type"]>;

	/**
	 * The meeting type to query. 
	 * - `all` - rerturn meetings and webinars 
	 * - `meeting` - only return meetings 
	 * - `webinar` - only return webinars
	 */
	readonly meetingType?: Sendable<ListReportHistoryMeetingsWireQuery["meeting_type"]>;

	/**
	 * Query meetings that have this type of report.
	 * - `all` - all meetings
	 * - `poll` - meetings with poll data 
	 * - `survey` - meetings with survey data 
	 * - `qa` - meetings with Q&A data 
	 * - `resource` - meetings with resource link data 
	 * - `reaction` - meetings with reaction data
	 */
	readonly reportType?: Sendable<ListReportHistoryMeetingsWireQuery["report_type"]>;

	/** The keywords of meeting topic or meeting ID. */
	readonly searchKey?: Sendable<ListReportHistoryMeetingsWireQuery["search_key"]>;

	/** The number of records to be returned within a single API call. */
	readonly pageSize?: Sendable<ListReportHistoryMeetingsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportHistoryMeetingsWireQuery["next_page_token"]>;

	/**
	 * The group ID. To get a group ID, use the [**List groups**](/docs/api/rest/reference/user/methods/#operation/groups) API. 
	 *
	 *  **Note:** The API response will only contain users who are members of the queried group ID.
	 */
	readonly groupId?: Sendable<ListReportHistoryMeetingsWireQuery["group_id"]>;

	/** The meeting features to query and return history meetings that use one or more of these features. To provide multiple values, separate them with commas, like `meeting_summary,meeting_questions` */
	readonly meetingFeature?: Sendable<ListReportHistoryMeetingsWireQuery["meeting_feature"]>;
}

/** What {@link listReportHistoryMeetings} resolves to. */
export type ListReportHistoryMeetingsResponse =
	paths["/report/history_meetings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/history_meetings`
 *
 * Get history meeting and webinar list
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:list_history_meetings:admin` and openapi_authorization: header `Authorization`
 */
export function listReportHistoryMeetings(
	query: ListReportHistoryMeetingsQuery,
): Operation<ListReportHistoryMeetingsResponse> {
	return {
		method: "GET",
		path: "/report/history_meetings",
		query: {
			from: query.from,
			to: query.to,
			date_type: query.dateType,
			meeting_type: query.meetingType,
			report_type: query.reportType,
			search_key: query.searchKey,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			group_id: query.groupId,
			meeting_feature: query.meetingFeature,
		},
	};
}

type ListReportMeetingActivitiesWireQuery = NonNullable<paths["/report/meeting_activities"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportMeetingActivities}. */
export interface ListReportMeetingActivitiesQuery {
	/** The start date in 'yyyy-MM-dd'format. The date range defined by the `from` and `to` parameters should only be one month, as the report includes only one month's worth of data at once. */
	readonly from: Sendable<ListReportMeetingActivitiesWireQuery["from"]>;

	/** The end date 'yyyy-MM-dd' format. */
	readonly to: Sendable<ListReportMeetingActivitiesWireQuery["to"]>;

	/** The number of records to be returned within a single API call. */
	readonly pageSize?: Sendable<ListReportMeetingActivitiesWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportMeetingActivitiesWireQuery["next_page_token"]>;

	/** The meeting's number. */
	readonly meetingNumber?: Sendable<ListReportMeetingActivitiesWireQuery["meeting_number"]>;

	/** An operator's name or email. */
	readonly searchKey?: Sendable<ListReportMeetingActivitiesWireQuery["search_key"]>;

	/**
	 * Activity type. 
	 * -1 - All activities. 
	 * 0 - Meeting created. 
	 * 1 - Meeting started. 
	 * 2 - User joined. 
	 * 3 - User left. 
	 * 4 - Remote control. 
	 * 5 - In-meeting chat. 
	 * 9 - Meeting ended.
	 */
	readonly activityType: Sendable<ListReportMeetingActivitiesWireQuery["activity_type"]>;
}

/** What {@link listReportMeetingActivities} resolves to. */
export type ListReportMeetingActivitiesResponse =
	paths["/report/meeting_activities"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/meeting_activities`
 *
 * Get a meeting activities report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:meeting_activity_log:admin` and openapi_authorization: header `Authorization`
 */
export function listReportMeetingActivities(
	query: ListReportMeetingActivitiesQuery,
): Operation<ListReportMeetingActivitiesResponse> {
	return {
		method: "GET",
		path: "/report/meeting_activities",
		query: {
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			meeting_number: query.meetingNumber,
			search_key: query.searchKey,
			activity_type: query.activityType,
		},
	};
}

type GetReportMeetingWirePath = NonNullable<paths["/report/meetings/{meetingId}"]["get"]["parameters"]["path"]>;

/** What {@link getReportMeeting} resolves to. */
export type GetReportMeetingResponse =
	paths["/report/meetings/{meetingId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/meetings/{meetingId}`
 *
 * Get meeting detail reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:meeting:admin` and openapi_authorization: header `Authorization`
 */
export function getReportMeeting(
	meetingId: GetReportMeetingWirePath["meetingId"],
): Operation<GetReportMeetingResponse> {
	return {
		method: "GET",
		path: `/report/meetings/${encodeURIComponent(String(meetingId))}`,
	};
}

type ListReportMeetingParticipantsWirePath = NonNullable<paths["/report/meetings/{meetingId}/participants"]["get"]["parameters"]["path"]>;

type ListReportMeetingParticipantsWireQuery = NonNullable<paths["/report/meetings/{meetingId}/participants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportMeetingParticipants}. */
export interface ListReportMeetingParticipantsQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListReportMeetingParticipantsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportMeetingParticipantsWireQuery["next_page_token"]>;

	/** Provide `registrant_id` as the value for this field if you would like to see the registrant ID attribute in the response of this API call. A registrant ID is a unique identifier of a [meeting registrant](/docs/api-reference/zoom-api/methods#operation/meetingRegistrants). */
	readonly includeFields?: Sendable<ListReportMeetingParticipantsWireQuery["include_fields"]>;
}

/** What {@link listReportMeetingParticipants} resolves to. */
export type ListReportMeetingParticipantsResponse =
	paths["/report/meetings/{meetingId}/participants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/meetings/{meetingId}/participants`
 *
 * Get meeting participant reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:list_meeting_participants:admin` and openapi_authorization: header `Authorization`
 */
export function listReportMeetingParticipants(
	meetingId: ListReportMeetingParticipantsWirePath["meetingId"],
	query: ListReportMeetingParticipantsQuery = {},
): Operation<ListReportMeetingParticipantsResponse> {
	return {
		method: "GET",
		path: `/report/meetings/${encodeURIComponent(String(meetingId))}/participants`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			include_fields: query.includeFields,
		},
	};
}

type ListReportMeetingPollsWirePath = NonNullable<paths["/report/meetings/{meetingId}/polls"]["get"]["parameters"]["path"]>;

/** What {@link listReportMeetingPolls} resolves to. */
export type ListReportMeetingPollsResponse =
	paths["/report/meetings/{meetingId}/polls"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/meetings/{meetingId}/polls`
 *
 * Get meeting poll reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:list_meeting_polls:admin` and openapi_authorization: header `Authorization`
 */
export function listReportMeetingPolls(
	meetingId: ListReportMeetingPollsWirePath["meetingId"],
): Operation<ListReportMeetingPollsResponse> {
	return {
		method: "GET",
		path: `/report/meetings/${encodeURIComponent(String(meetingId))}/polls`,
	};
}

type GetReportMeetingQaWirePath = NonNullable<paths["/report/meetings/{meetingId}/qa"]["get"]["parameters"]["path"]>;

/** What {@link getReportMeetingQa} resolves to. */
export type GetReportMeetingQaResponse =
	paths["/report/meetings/{meetingId}/qa"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/meetings/{meetingId}/qa`
 *
 * Get meeting Q&A report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:meeting_qna:admin` and openapi_authorization: header `Authorization`
 */
export function getReportMeetingQa(
	meetingId: GetReportMeetingQaWirePath["meetingId"],
): Operation<GetReportMeetingQaResponse> {
	return {
		method: "GET",
		path: `/report/meetings/${encodeURIComponent(String(meetingId))}/qa`,
	};
}

type GetReportMeetingSurveyWirePath = NonNullable<paths["/report/meetings/{meetingId}/survey"]["get"]["parameters"]["path"]>;

/** What {@link getReportMeetingSurvey} resolves to. */
export type GetReportMeetingSurveyResponse =
	paths["/report/meetings/{meetingId}/survey"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/meetings/{meetingId}/survey`
 *
 * Get meeting survey report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:meeting_survey:admin` and openapi_authorization: header `Authorization`
 */
export function getReportMeetingSurvey(
	meetingId: GetReportMeetingSurveyWirePath["meetingId"],
): Operation<GetReportMeetingSurveyResponse> {
	return {
		method: "GET",
		path: `/report/meetings/${encodeURIComponent(String(meetingId))}/survey`,
	};
}

type ListReportOperationlogsWireQuery = NonNullable<paths["/report/operationlogs"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportOperationlogs}. */
export interface ListReportOperationlogsQuery {
	/** Start date in 'yyyy-mm-dd' or 'yyyy-MM-dd HH:mm' format. The date range defined by the `from` and `to` parameters should only be one month as the report includes only one month worth of data at once. */
	readonly from: Sendable<ListReportOperationlogsWireQuery["from"]>;

	/** End date in 'yyyy-mm-dd' or 'yyyy-MM-dd HH:mm' format. */
	readonly to: Sendable<ListReportOperationlogsWireQuery["to"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListReportOperationlogsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportOperationlogsWireQuery["next_page_token"]>;

	/**
	 * **Optional**  
	 *  
	 * Filter your response by a category type to see reports for a specific category.
	 * The value for this field can be one of the following:  
	 *   `all`  
	 *  `user`  
	 *  `user_settings`  
	 *  `account`  
	 *  `billing`  
	 *  `im`  
	 *  `recording`  
	 *  `phone_contacts`  
	 *  `webinar`  
	 *  `sub_account`  
	 *  `role`  
	 *  `zoom_rooms`
	 */
	readonly categoryType?: Sendable<ListReportOperationlogsWireQuery["category_type"]>;
}

/** What {@link listReportOperationlogs} resolves to. */
export type ListReportOperationlogsResponse =
	paths["/report/operationlogs"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/operationlogs`
 *
 * Get operation logs report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:operation_logs:admin` and openapi_authorization: header `Authorization`
 */
export function listReportOperationlogs(
	query: ListReportOperationlogsQuery,
): Operation<ListReportOperationlogsResponse> {
	return {
		method: "GET",
		path: "/report/operationlogs",
		query: {
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			category_type: query.categoryType,
		},
	};
}

type GetReportRemoteSupportWireQuery = NonNullable<paths["/report/remote_support"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getReportRemoteSupport}. */
export interface GetReportRemoteSupportQuery {
	/** The start date in `yyyy-MM-dd` format. The date range defined by the `from` and `to` parameters should only be one month, as the report includes only one month's worth of data at once. It is the date range for remote support to start. */
	readonly from: Sendable<GetReportRemoteSupportWireQuery["from"]>;

	/** The end date in `yyyy-MM-dd` format. */
	readonly to: Sendable<GetReportRemoteSupportWireQuery["to"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<GetReportRemoteSupportWireQuery["next_page_token"]>;

	/** The number of records to be returned within a single API call. */
	readonly pageSize?: Sendable<GetReportRemoteSupportWireQuery["page_size"]>;
}

/** What {@link getReportRemoteSupport} resolves to. */
export type GetReportRemoteSupportResponse =
	paths["/report/remote_support"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/remote_support`
 *
 * Get remote support report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:remote_support:admin` and openapi_authorization: header `Authorization`
 */
export function getReportRemoteSupport(
	query: GetReportRemoteSupportQuery,
): Operation<GetReportRemoteSupportResponse> {
	return {
		method: "GET",
		path: "/report/remote_support",
		query: {
			from: query.from,
			to: query.to,
			next_page_token: query.nextPageToken,
			page_size: query.pageSize,
		},
	};
}

type GetReportTelephoneWireQuery = NonNullable<paths["/report/telephone"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getReportTelephone}. */
export interface GetReportTelephoneQuery {
	/**
	 * Audio types:  
	 *  `1` - Toll-free Call-in &amp; Call-out.  
	 *  `2` - Toll   
	 *  
	 * `3` - SIP Connected Audio
	 */
	readonly type?: Sendable<GetReportTelephoneWireQuery["type"]>;

	/**
	 * The type of date to query. 
	 * * `start_time` &mdash; Query by call start time. 
	 * * `end_time` &mdash; Query by call end time. 
	 * * `meeting_start_time` &mdash; Query by meeting start time. 
	 * * `meeting_end_time` &mdash; Query by meeting end time. 
	 *
	 * This value defaults to `start_time`.
	 */
	readonly queryDateType?: Sendable<GetReportTelephoneWireQuery["query_date_type"]>;

	/** Start date in 'yyyy-mm-dd' format. The date range defined by the &quot;from&quot; and &quot;to&quot; parameters should only be one month as the report includes only one month worth of data at once. */
	readonly from: Sendable<GetReportTelephoneWireQuery["from"]>;

	/** End date. */
	readonly to: Sendable<GetReportTelephoneWireQuery["to"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<GetReportTelephoneWireQuery["page_size"]>;

	/**
	 * The page number of the current page in the returned records. This field is **not** available if the `query_date_type` parameter is the `meeting_start_time` or `meeting_end_time` value. 
	 *
	 * This field is deprecated. Use the `next_page_token` query parameter for pagination.
	 */
	readonly pageNumber?: Sendable<GetReportTelephoneWireQuery["page_number"]>;

	/** Use the next page token to paginate through large result sets. A next page token will be returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<GetReportTelephoneWireQuery["next_page_token"]>;
}

/** What {@link getReportTelephone} resolves to. */
export type GetReportTelephoneResponse =
	paths["/report/telephone"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/telephone`
 *
 * Get telephone reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:telephone:admin` and openapi_authorization: header `Authorization`
 */
export function getReportTelephone(
	query: GetReportTelephoneQuery,
): Operation<GetReportTelephoneResponse> {
	return {
		method: "GET",
		path: "/report/telephone",
		query: {
			type: query.type,
			query_date_type: query.queryDateType,
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			page_number: query.pageNumber,
			next_page_token: query.nextPageToken,
		},
	};
}

type ListReportUpcomingEventsWireQuery = NonNullable<paths["/report/upcoming_events"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportUpcomingEvents}. */
export interface ListReportUpcomingEventsQuery {
	/** Start date in 'yyyy-mm-dd' format. The date range defined by the &quot;from&quot; and &quot;to&quot; parameters should only be one month as the report includes only one month worth of data at once. */
	readonly from: Sendable<ListReportUpcomingEventsWireQuery["from"]>;

	/** End date. */
	readonly to: Sendable<ListReportUpcomingEventsWireQuery["to"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListReportUpcomingEventsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportUpcomingEventsWireQuery["next_page_token"]>;

	/**
	 * The type of event to query. 
	 * * `meeting` &mdash; A meeting event. 
	 * * `webinar` &mdash; A webinar event. 
	 * * `all` &mdash; Both meeting and webinar events.
	 *
	 * This value defaults to `all`.
	 */
	readonly type?: Sendable<ListReportUpcomingEventsWireQuery["type"]>;

	/**
	 * The group ID. To get a group ID, use the [**List groups**](/api-reference/zoom-api/methods#operation/groups) API. 
	 *
	 *  **Note:** The API response will only contain meetings where the host is a member of the queried group ID.
	 */
	readonly groupId?: Sendable<ListReportUpcomingEventsWireQuery["group_id"]>;
}

/** What {@link listReportUpcomingEvents} resolves to. */
export type ListReportUpcomingEventsResponse =
	paths["/report/upcoming_events"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/upcoming_events`
 *
 * Get upcoming events report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:upcoming_meetings_webinars:admin` and openapi_authorization: header `Authorization`
 */
export function listReportUpcomingEvents(
	query: ListReportUpcomingEventsQuery,
): Operation<ListReportUpcomingEventsResponse> {
	return {
		method: "GET",
		path: "/report/upcoming_events",
		query: {
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			type: query.type,
			group_id: query.groupId,
		},
	};
}

type ListReportUsersWireQuery = NonNullable<paths["/report/users"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportUsers}. */
export interface ListReportUsersQuery {
	/**
	 * Active or inactive hosts.  
	 *  `active` - Active hosts.   
	 *  `inactive` - Inactive hosts.
	 */
	readonly type?: Sendable<ListReportUsersWireQuery["type"]>;

	/** Start date in 'yyyy-mm-dd' format. The date range defined by the `from` and `to` parameters should only be one month as the report includes only one month worth of data at once. */
	readonly from: Sendable<ListReportUsersWireQuery["from"]>;

	/** End date. */
	readonly to: Sendable<ListReportUsersWireQuery["to"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListReportUsersWireQuery["page_size"]>;

	/** The page number of the current page in the returned records. */
	readonly pageNumber?: Sendable<ListReportUsersWireQuery["page_number"]>;

	/** The next page token is used to paginate through large result sets. A next page token will be returned whenever the set of available results exceeds the current page size. The expiration period for this token is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportUsersWireQuery["next_page_token"]>;

	/**
	 * The group ID. To get a group ID, use the [**List groups**](/docs/api/rest/reference/user/methods/#operation/groups) API. 
	 *
	 *  **Note:** The API response will only contain users who are members of the queried group ID.
	 */
	readonly groupId?: Sendable<ListReportUsersWireQuery["group_id"]>;
}

/** What {@link listReportUsers} resolves to. */
export type ListReportUsersResponse =
	paths["/report/users"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/users`
 *
 * Get active or inactive host reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:list_users:admin` and openapi_authorization: header `Authorization`
 */
export function listReportUsers(
	query: ListReportUsersQuery,
): Operation<ListReportUsersResponse> {
	return {
		method: "GET",
		path: "/report/users",
		query: {
			type: query.type,
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			page_number: query.pageNumber,
			next_page_token: query.nextPageToken,
			group_id: query.groupId,
		},
	};
}

type ListReportUserMeetingsWirePath = NonNullable<paths["/report/users/{userId}/meetings"]["get"]["parameters"]["path"]>;

type ListReportUserMeetingsWireQuery = NonNullable<paths["/report/users/{userId}/meetings"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportUserMeetings}. */
export interface ListReportUserMeetingsQuery {
	/** Start date in 'yyyy-mm-dd' format. The date range defined by the &quot;from&quot; and &quot;to&quot; parameters should only be one month as the report includes only one month worth of data at once. */
	readonly from: Sendable<ListReportUserMeetingsWireQuery["from"]>;

	/** End date. */
	readonly to: Sendable<ListReportUserMeetingsWireQuery["to"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListReportUserMeetingsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportUserMeetingsWireQuery["next_page_token"]>;

	/**
	 * The meeting type to query for: 
	 * * `past` - All past meetings. 
	 * * `pastOne` - A single past user meeting. 
	 * * `pastJoined` - All past meetings the account's users hosted or joined.
	 */
	readonly type?: Sendable<ListReportUserMeetingsWireQuery["type"]>;
}

/** What {@link listReportUserMeetings} resolves to. */
export type ListReportUserMeetingsResponse =
	paths["/report/users/{userId}/meetings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/users/{userId}/meetings`
 *
 * Get meeting reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:user:admin` and openapi_authorization: header `Authorization`
 */
export function listReportUserMeetings(
	userId: ListReportUserMeetingsWirePath["userId"],
	query: ListReportUserMeetingsQuery,
): Operation<ListReportUserMeetingsResponse> {
	return {
		method: "GET",
		path: `/report/users/${encodeURIComponent(String(userId))}/meetings`,
		query: {
			from: query.from,
			to: query.to,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			type: query.type,
		},
	};
}

type GetReportWebinarWirePath = NonNullable<paths["/report/webinars/{webinarId}"]["get"]["parameters"]["path"]>;

/** What {@link getReportWebinar} resolves to. */
export type GetReportWebinarResponse =
	paths["/report/webinars/{webinarId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/webinars/{webinarId}`
 *
 * Get webinar detail reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:webinar:admin` and openapi_authorization: header `Authorization`
 */
export function getReportWebinar(
	webinarId: GetReportWebinarWirePath["webinarId"],
): Operation<GetReportWebinarResponse> {
	return {
		method: "GET",
		path: `/report/webinars/${encodeURIComponent(String(webinarId))}`,
	};
}

type ListReportWebinarParticipantsWirePath = NonNullable<paths["/report/webinars/{webinarId}/participants"]["get"]["parameters"]["path"]>;

type ListReportWebinarParticipantsWireQuery = NonNullable<paths["/report/webinars/{webinarId}/participants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listReportWebinarParticipants}. */
export interface ListReportWebinarParticipantsQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListReportWebinarParticipantsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListReportWebinarParticipantsWireQuery["next_page_token"]>;

	/**
	 * The additional query parameters to include. 
	 * * `registrant_id` - Include the registrant's ID in the API response. The registrant ID is the webinar participant's unique ID.
	 */
	readonly includeFields?: Sendable<ListReportWebinarParticipantsWireQuery["include_fields"]>;
}

/** What {@link listReportWebinarParticipants} resolves to. */
export type ListReportWebinarParticipantsResponse =
	paths["/report/webinars/{webinarId}/participants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/webinars/{webinarId}/participants`
 *
 * Get webinar participant reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:list_webinar_participants:admin` and openapi_authorization: header `Authorization`
 */
export function listReportWebinarParticipants(
	webinarId: ListReportWebinarParticipantsWirePath["webinarId"],
	query: ListReportWebinarParticipantsQuery = {},
): Operation<ListReportWebinarParticipantsResponse> {
	return {
		method: "GET",
		path: `/report/webinars/${encodeURIComponent(String(webinarId))}/participants`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			include_fields: query.includeFields,
		},
	};
}

type ListReportWebinarPollsWirePath = NonNullable<paths["/report/webinars/{webinarId}/polls"]["get"]["parameters"]["path"]>;

/** What {@link listReportWebinarPolls} resolves to. */
export type ListReportWebinarPollsResponse =
	paths["/report/webinars/{webinarId}/polls"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/webinars/{webinarId}/polls`
 *
 * Get webinar poll reports
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:list_webinar_polls:admin` and openapi_authorization: header `Authorization`
 */
export function listReportWebinarPolls(
	webinarId: ListReportWebinarPollsWirePath["webinarId"],
): Operation<ListReportWebinarPollsResponse> {
	return {
		method: "GET",
		path: `/report/webinars/${encodeURIComponent(String(webinarId))}/polls`,
	};
}

type GetReportWebinarQaWirePath = NonNullable<paths["/report/webinars/{webinarId}/qa"]["get"]["parameters"]["path"]>;

/** What {@link getReportWebinarQa} resolves to. */
export type GetReportWebinarQaResponse =
	paths["/report/webinars/{webinarId}/qa"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/webinars/{webinarId}/qa`
 *
 * Get webinar Q&A report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:webinar_qna:admin` and openapi_authorization: header `Authorization`
 */
export function getReportWebinarQa(
	webinarId: GetReportWebinarQaWirePath["webinarId"],
): Operation<GetReportWebinarQaResponse> {
	return {
		method: "GET",
		path: `/report/webinars/${encodeURIComponent(String(webinarId))}/qa`,
	};
}

type GetReportWebinarSurveyWirePath = NonNullable<paths["/report/webinars/{webinarId}/survey"]["get"]["parameters"]["path"]>;

/** What {@link getReportWebinarSurvey} resolves to. */
export type GetReportWebinarSurveyResponse =
	paths["/report/webinars/{webinarId}/survey"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /report/webinars/{webinarId}/survey`
 *
 * Get webinar survey report
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `report:read:admin` `report:read:webinar_survey:admin` and openapi_authorization: header `Authorization`
 */
export function getReportWebinarSurvey(
	webinarId: GetReportWebinarSurveyWirePath["webinarId"],
): Operation<GetReportWebinarSurveyResponse> {
	return {
		method: "GET",
		path: `/report/webinars/${encodeURIComponent(String(webinarId))}/survey`,
	};
}
