// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListSipPhonePhonesWireQuery = NonNullable<paths["/sip_phones/phones"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listSipPhonePhones}. */
export interface ListSipPhonePhonesQuery {
	/** A user's user name or email address. If this parameter is provided, only the SIP phone system integration enabled for that specific user will be returned. Otherwise, all SIP phones on an account will be returned. */
	readonly searchKey?: Sendable<ListSipPhonePhonesWireQuery["search_key"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListSipPhonePhonesWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token will be returned whenever the set of available results exceeds the current page size. This tokan's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListSipPhonePhonesWireQuery["next_page_token"]>;
}

/** What {@link listSipPhonePhones} resolves to. */
export type ListSipPhonePhonesResponse =
	paths["/sip_phones/phones"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /sip_phones/phones`
 *
 * List SIP phones
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `sip_phone:read:admin` `sip_phone:read:list_sip_phones:admin` and openapi_authorization: header `Authorization`
 */
export function listSipPhonePhones(
	query: ListSipPhonePhonesQuery = {},
): Operation<ListSipPhonePhonesResponse> {
	return {
		method: "GET",
		path: "/sip_phones/phones",
		query: {
			search_key: query.searchKey,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
		},
	};
}

/** Body accepted by {@link createSipPhonePhone}. */
export type CreateSipPhonePhoneBody = NonNullable<paths["/sip_phones/phones"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createSipPhonePhone} resolves to. */
export type CreateSipPhonePhoneResponse =
	paths["/sip_phones/phones"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /sip_phones/phones`
 *
 * Enable SIP phone
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `sip_phone:write:admin` `sip_phone:write:sip_phone:admin` and openapi_authorization: header `Authorization`
 */
export function createSipPhonePhone(
	input: CreateSipPhonePhoneBody,
): Operation<CreateSipPhonePhoneResponse> {
	return {
		method: "POST",
		path: "/sip_phones/phones",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type UpdateSipPhonePhoneWirePath = NonNullable<paths["/sip_phones/phones/{phoneId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateSipPhonePhone}. */
export type UpdateSipPhonePhoneBody = NonNullable<paths["/sip_phones/phones/{phoneId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /sip_phones/phones/{phoneId}`
 *
 * Update SIP phone
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `sip_phone:write:admin` `sip_phone:update:sip_phone:admin` and openapi_authorization: header `Authorization`
 */
export function updateSipPhonePhone(
	phoneId: UpdateSipPhonePhoneWirePath["phoneId"],
	patch: UpdateSipPhonePhoneBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/sip_phones/phones/${encodeURIComponent(String(phoneId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteSipPhonePhoneWirePath = NonNullable<paths["/sip_phones/phones/{phoneId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /sip_phones/phones/{phoneId}`
 *
 * Delete SIP phone
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `sip_phone:write:admin` `sip_phone:delete:sip_phone:admin` and openapi_authorization: header `Authorization`
 */
export function deleteSipPhonePhone(
	phoneId: DeleteSipPhonePhoneWirePath["phoneId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/sip_phones/phones/${encodeURIComponent(String(phoneId))}`,
		decode: async () => undefined,
	};
}
