// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation } from "../operation.js";
import type { paths } from "../schema.js";

/** What {@link listTrackingFields} resolves to. */
export type ListTrackingFieldsResponse =
	paths["/tracking_fields"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /tracking_fields`
 *
 * List tracking fields
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tracking_fields:read:admin` `tracking_field:read:list_tracking_fields:admin` and openapi_authorization: header `Authorization`
 */
export function listTrackingFields(): Operation<ListTrackingFieldsResponse> {
	return {
		method: "GET",
		path: "/tracking_fields",
	};
}

/** Body accepted by {@link createTrackingField}. */
export type CreateTrackingFieldBody = NonNullable<paths["/tracking_fields"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createTrackingField} resolves to. */
export type CreateTrackingFieldResponse =
	paths["/tracking_fields"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /tracking_fields`
 *
 * Create a tracking field
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tracking_fields:write:admin` `tracking_field:write:tracking_field:admin` and openapi_authorization: header `Authorization`
 */
export function createTrackingField(
	input: CreateTrackingFieldBody,
): Operation<CreateTrackingFieldResponse> {
	return {
		method: "POST",
		path: "/tracking_fields",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetTrackingFieldWirePath = NonNullable<paths["/tracking_fields/{fieldId}"]["get"]["parameters"]["path"]>;

/** What {@link getTrackingField} resolves to. */
export type GetTrackingFieldResponse =
	paths["/tracking_fields/{fieldId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /tracking_fields/{fieldId}`
 *
 * Get a tracking field
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tracking_fields:read:admin` `tracking_field:read:tracking_field:admin` and openapi_authorization: header `Authorization`
 */
export function getTrackingField(
	fieldId: GetTrackingFieldWirePath["fieldId"],
): Operation<GetTrackingFieldResponse> {
	return {
		method: "GET",
		path: `/tracking_fields/${encodeURIComponent(String(fieldId))}`,
	};
}

type UpdateTrackingFieldWirePath = NonNullable<paths["/tracking_fields/{fieldId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateTrackingField}. */
export type UpdateTrackingFieldBody = NonNullable<paths["/tracking_fields/{fieldId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /tracking_fields/{fieldId}`
 *
 * Update a tracking field
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tracking_fields:write:admin` `tracking_field:update:tracking_field:admin` and openapi_authorization: header `Authorization`
 */
export function updateTrackingField(
	fieldId: UpdateTrackingFieldWirePath["fieldId"],
	patch: UpdateTrackingFieldBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/tracking_fields/${encodeURIComponent(String(fieldId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteTrackingFieldWirePath = NonNullable<paths["/tracking_fields/{fieldId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /tracking_fields/{fieldId}`
 *
 * Delete a tracking field
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tracking_fields:write:admin` `tracking_field:delete:tracking_field:admin` and openapi_authorization: header `Authorization`
 */
export function deleteTrackingField(
	fieldId: DeleteTrackingFieldWirePath["fieldId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/tracking_fields/${encodeURIComponent(String(fieldId))}`,
		decode: async () => undefined,
	};
}
