// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation } from "../operation.js";
import type { paths } from "../schema.js";

/** What {@link getTsp} resolves to. */
export type GetTspResponse =
	paths["/tsp"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /tsp`
 *
 * Get account's TSP information
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:read:admin` `tsp:read:tsp:admin` and openapi_authorization: header `Authorization`
 */
export function getTsp(): Operation<GetTspResponse> {
	return {
		method: "GET",
		path: "/tsp",
	};
}

/** Body accepted by {@link updateTsp}. */
export type UpdateTspBody = NonNullable<paths["/tsp"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /tsp`
 *
 * Update an account's TSP information
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:write:admin` `tsp:update:tsp:admin` and openapi_authorization: header `Authorization`
 */
export function updateTsp(patch: UpdateTspBody): Operation<void> {
	return {
		method: "PATCH",
		path: "/tsp",
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}
