// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type ListUserMeetingSummariesWirePath = NonNullable<paths["/users/{userId}/meeting_summaries"]["get"]["parameters"]["path"]>;

type ListUserMeetingSummariesWireQuery = NonNullable<paths["/users/{userId}/meeting_summaries"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listUserMeetingSummaries}. */
export interface ListUserMeetingSummariesQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListUserMeetingSummariesWireQuery["page_size"]>;

	/** Use the next page token to paginate through a large set of results. The next page token returns whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListUserMeetingSummariesWireQuery["next_page_token"]>;

	/** The start date, in `yyyy-MM-dd'T'HH:mm:ss'Z'` UTC format. The time field used for filtering is specified by `time_filter_field`. */
	readonly from?: Sendable<ListUserMeetingSummariesWireQuery["from"]>;

	/** The end date, in `yyyy-MM-dd'T'HH:mm:ss'Z'` UTC format. The time field used for filtering is specified by `time_filter_field`. */
	readonly to?: Sendable<ListUserMeetingSummariesWireQuery["to"]>;

	/** Which summary time field to use to filter results by the `from` and `to` parameters. */
	readonly timeFilterField?: Sendable<ListUserMeetingSummariesWireQuery["time_filter_field"]>;
}

/** What {@link listUserMeetingSummaries} resolves to. */
export type ListUserMeetingSummariesResponse =
	paths["/users/{userId}/meeting_summaries"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/meeting_summaries`
 *
 * List a user's meeting or webinar summaries
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting_summary:read` `meeting_summary:read:admin` `meeting:read:list_summaries` `meeting:read:list_summaries:admin` and openapi_authorization: header `Authorization`
 */
export function listUserMeetingSummaries(
	userId: ListUserMeetingSummariesWirePath["userId"],
	query: ListUserMeetingSummariesQuery = {},
): Operation<ListUserMeetingSummariesResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/meeting_summaries`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			from: query.from,
			to: query.to,
			time_filter_field: query.timeFilterField,
		},
	};
}

type ListUserMeetingTemplatesWirePath = NonNullable<paths["/users/{userId}/meeting_templates"]["get"]["parameters"]["path"]>;

/** What {@link listUserMeetingTemplates} resolves to. */
export type ListUserMeetingTemplatesResponse =
	paths["/users/{userId}/meeting_templates"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/meeting_templates`
 *
 * List meeting templates
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:list_templates` `meeting:read:list_templates:admin` and openapi_authorization: header `Authorization`
 */
export function listUserMeetingTemplates(
	userId: ListUserMeetingTemplatesWirePath["userId"],
): Operation<ListUserMeetingTemplatesResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/meeting_templates`,
	};
}

type CreateUserMeetingTemplateWirePath = NonNullable<paths["/users/{userId}/meeting_templates"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createUserMeetingTemplate}. */
export type CreateUserMeetingTemplateBody = NonNullable<paths["/users/{userId}/meeting_templates"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createUserMeetingTemplate} resolves to. */
export type CreateUserMeetingTemplateResponse =
	paths["/users/{userId}/meeting_templates"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /users/{userId}/meeting_templates`
 *
 * Create a meeting template from an existing meeting
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:write:template` `meeting:write:template:admin` and openapi_authorization: header `Authorization`
 */
export function createUserMeetingTemplate(
	userId: CreateUserMeetingTemplateWirePath["userId"],
	input: CreateUserMeetingTemplateBody,
): Operation<CreateUserMeetingTemplateResponse> {
	return {
		method: "POST",
		path: `/users/${encodeURIComponent(String(userId))}/meeting_templates`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ListUserMeetingsWirePath = NonNullable<paths["/users/{userId}/meetings"]["get"]["parameters"]["path"]>;

type ListUserMeetingsWireQuery = NonNullable<paths["/users/{userId}/meetings"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listUserMeetings}. */
export interface ListUserMeetingsQuery {
	/**
	 * The meeting type. 
	 * * `scheduled` - All valid previous (unexpired) meetings, live meetings, and upcoming scheduled meetings. 
	 * * `live` - All the ongoing meetings. 
	 * * `upcoming` - All upcoming meetings, including live meetings. 
	 * * `upcoming_meetings` - All upcoming meetings, including live meetings. 
	 * * `previous_meetings` - All valid previous meetings whose scheduled end time has already passed.
	 */
	readonly type?: Sendable<ListUserMeetingsWireQuery["type"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListUserMeetingsWireQuery["page_size"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListUserMeetingsWireQuery["next_page_token"]>;

	/** The page number of the current page in the returned records. */
	readonly pageNumber?: Sendable<ListUserMeetingsWireQuery["page_number"]>;

	/** The start date. */
	readonly from?: Sendable<ListUserMeetingsWireQuery["from"]>;

	/** The end date. */
	readonly to?: Sendable<ListUserMeetingsWireQuery["to"]>;

	/** The timezone to assign to the `from` and `to` value. For a list of supported timezones and their formats, see our [timezone list](/docs/api/references/abbreviations/#timezones). */
	readonly timezone?: Sendable<ListUserMeetingsWireQuery["timezone"]>;
}

/** What {@link listUserMeetings} resolves to. */
export type ListUserMeetingsResponse =
	paths["/users/{userId}/meetings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/meetings`
 *
 * List meetings
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read:admin` `meeting:read` `meeting:read:list_meetings` `meeting:read:list_meetings:admin` and openapi_authorization: header `Authorization`
 */
export function listUserMeetings(
	userId: ListUserMeetingsWirePath["userId"],
	query: ListUserMeetingsQuery = {},
): Operation<ListUserMeetingsResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/meetings`,
		query: {
			type: query.type,
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			page_number: query.pageNumber,
			from: query.from,
			to: query.to,
			timezone: query.timezone,
		},
	};
}

type CreateUserMeetingWirePath = NonNullable<paths["/users/{userId}/meetings"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createUserMeeting}. */
export type CreateUserMeetingBody = NonNullable<paths["/users/{userId}/meetings"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createUserMeeting} resolves to. */
export type CreateUserMeetingResponse =
	paths["/users/{userId}/meetings"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /users/{userId}/meetings`
 *
 * Create a meeting
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:write:admin` `meeting:write` `meeting:write:meeting` `meeting:write:meeting:admin` and openapi_authorization: header `Authorization`
 */
export function createUserMeeting(
	userId: CreateUserMeetingWirePath["userId"],
	input: CreateUserMeetingBody,
): Operation<CreateUserMeetingResponse> {
	return {
		method: "POST",
		path: `/users/${encodeURIComponent(String(userId))}/meetings`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetUserPacWirePath = NonNullable<paths["/users/{userId}/pac"]["get"]["parameters"]["path"]>;

/** What {@link getUserPac} resolves to. */
export type GetUserPacResponse =
	paths["/users/{userId}/pac"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/pac`
 *
 * List a user's PAC accounts
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `pac:read:admin` `pac:read` `pac:read:list_pac_accounts` `pac:read:list_pac_accounts:admin` and openapi_authorization: header `Authorization`
 */
export function getUserPac(
	userId: GetUserPacWirePath["userId"],
): Operation<GetUserPacResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/pac`,
	};
}

type ListUserRecordingsWirePath = NonNullable<paths["/users/{userId}/recordings"]["get"]["parameters"]["path"]>;

type ListUserRecordingsWireQuery = NonNullable<paths["/users/{userId}/recordings"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listUserRecordings}. */
export interface ListUserRecordingsQuery {
	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListUserRecordingsWireQuery["page_size"]>;

	/** The next page token paginates through a large set of results. A next page token returns whenever the set of available results exceeds the current page size. The expiration period for this token is 15 minutes. */
	readonly nextPageToken?: Sendable<ListUserRecordingsWireQuery["next_page_token"]>;

	/** The query metadata of the recording if using an on-premise meeting connector for the meeting. */
	readonly mc?: Sendable<ListUserRecordingsWireQuery["mc"]>;

	/**
	 * The query trash.
	 * * `true` - List recordings from trash.  
	 * * `false` - Do not list recordings from the trash.  
	 *
	 * The default value is `false`. If you set it to `true`, you can use the `trash_type` property to indicate the type of Cloud recording that you need to retrieve. 
	 */
	readonly trash?: Sendable<ListUserRecordingsWireQuery["trash"]>;

	/**
	 * The start date in 'yyyy-mm-dd' UTC format for the date range where you would like to retrieve recordings. The maximum range can be a month. If no value is provided for this field, the default will be current date. 
	 *
	 * For example, if you make the API request on June 30, 2020, without providing the `from` and `to` parameters, by default the value of 'from' field will be `2020-06-30` and the value of the 'to' field will be `2020-07-01`. 
	 *
	 * **Note**: The `trash` files cannot be filtered by date range and thus, the `from` and `to` fields should not be used for trash files.
	 */
	readonly from?: Sendable<ListUserRecordingsWireQuery["from"]>;

	/** The end date in 'yyyy-mm-dd' 'yyyy-mm-dd' UTC format.  */
	readonly to?: Sendable<ListUserRecordingsWireQuery["to"]>;

	/**
	 * The type of cloud recording to retrieve from the trash. 
	 *  
	 *  *   `meeting_recordings`: List all meeting recordings from the trash.  
	 *  *  `recording_file`: List all individual recording files from the trash. 
	 */
	readonly trashType?: Sendable<ListUserRecordingsWireQuery["trash_type"]>;

	/** The meeting ID. */
	readonly meetingId?: Sendable<ListUserRecordingsWireQuery["meeting_id"]>;

	/**
	 * The Zoom Revenue Accelerator (ZRA) analysis status of a recording.
	 *
	 * * `all` - all Revenue Accelerator status.
	 * *  `added`: added to Revenue Accelerator.
	 * *  `not_added`: not added to Revenue Accelerator.
	 * *  `processing`: processing Revenue Accelerator analysis.
	 */
	readonly zraStatus?: Sendable<ListUserRecordingsWireQuery["zra_status"]>;

	/**
	 * * `null` - Return all recordings, including cloud recordings and My Notes recordings.
	 * * `cloud_recording_only` - Return only cloud recordings.
	 * * `my_notes_recording_only` - Return only My Notes recordings.
	 */
	readonly recordingSourceType?: Sendable<ListUserRecordingsWireQuery["recording_source_type"]>;
}

/** What {@link listUserRecordings} resolves to. */
export type ListUserRecordingsResponse =
	paths["/users/{userId}/recordings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/recordings`
 *
 * List all recordings
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `recording:read:admin` `recording:read` `cloud_recording:read:list_user_recordings` `cloud_recording:read:list_user_recordings:master` `cloud_recording:read:list_user_recordings:admin` and openapi_authorization: header `Authorization`
 */
export function listUserRecordings(
	userId: ListUserRecordingsWirePath["userId"],
	query: ListUserRecordingsQuery = {},
): Operation<ListUserRecordingsResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/recordings`,
		query: {
			page_size: query.pageSize,
			next_page_token: query.nextPageToken,
			mc: query.mc,
			trash: query.trash,
			from: query.from,
			to: query.to,
			trash_type: query.trashType,
			meeting_id: query.meetingId,
			zra_status: query.zraStatus,
			recording_source_type: query.recordingSourceType,
		},
	};
}

type ListUserTspWirePath = NonNullable<paths["/users/{userId}/tsp"]["get"]["parameters"]["path"]>;

/** What {@link listUserTsp} resolves to. */
export type ListUserTspResponse =
	paths["/users/{userId}/tsp"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/tsp`
 *
 * List user's TSP accounts
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:read:admin` `tsp:read` `tsp:read:list_tsp_accounts` `tsp:read:list_tsp_accounts:admin` and openapi_authorization: header `Authorization`
 */
export function listUserTsp(
	userId: ListUserTspWirePath["userId"],
): Operation<ListUserTspResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/tsp`,
	};
}

type CreateUserTspWirePath = NonNullable<paths["/users/{userId}/tsp"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createUserTsp}. */
export type CreateUserTspBody = NonNullable<paths["/users/{userId}/tsp"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createUserTsp} resolves to. */
export type CreateUserTspResponse =
	paths["/users/{userId}/tsp"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /users/{userId}/tsp`
 *
 * Add a user's TSP account
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:write:admin` `tsp:write` `tsp:write:tsp_account` `tsp:write:tsp_account:admin` and openapi_authorization: header `Authorization`
 */
export function createUserTsp(
	userId: CreateUserTspWirePath["userId"],
	input: CreateUserTspBody,
): Operation<CreateUserTspResponse> {
	return {
		method: "POST",
		path: `/users/${encodeURIComponent(String(userId))}/tsp`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type UpdateUserTspSettingsWirePath = NonNullable<paths["/users/{userId}/tsp/settings"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateUserTspSettings}. */
export type UpdateUserTspSettingsBody = NonNullable<paths["/users/{userId}/tsp/settings"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /users/{userId}/tsp/settings`
 *
 * Set global dial-in URL for a TSP user
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:write:admin` `tsp:write` `tsp:update:tsp_settings` `tsp:update:tsp_settings:admin` and openapi_authorization: header `Authorization`
 */
export function updateUserTspSettings(
	userId: UpdateUserTspSettingsWirePath["userId"],
	patch: UpdateUserTspSettingsBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/users/${encodeURIComponent(String(userId))}/tsp/settings`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type GetUserTspWirePath = NonNullable<paths["/users/{userId}/tsp/{tspId}"]["get"]["parameters"]["path"]>;

/** What {@link getUserTsp} resolves to. */
export type GetUserTspResponse =
	paths["/users/{userId}/tsp/{tspId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/tsp/{tspId}`
 *
 * Get a user's TSP account
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:read:admin` `tsp:read` `tsp:read:tsp_account` `tsp:read:tsp_account:admin` and openapi_authorization: header `Authorization`
 */
export function getUserTsp(
	userId: GetUserTspWirePath["userId"],
	tspId: GetUserTspWirePath["tspId"],
): Operation<GetUserTspResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/tsp/${encodeURIComponent(String(tspId))}`,
	};
}

type UpdateUserTspWirePath = NonNullable<paths["/users/{userId}/tsp/{tspId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateUserTsp}. */
export type UpdateUserTspBody = NonNullable<paths["/users/{userId}/tsp/{tspId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /users/{userId}/tsp/{tspId}`
 *
 * Update a TSP account
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:write:admin` `tsp:write` `tsp:update:tsp_account` `tsp:update:tsp_account:admin` and openapi_authorization: header `Authorization`
 */
export function updateUserTsp(
	userId: UpdateUserTspWirePath["userId"],
	tspId: UpdateUserTspWirePath["tspId"],
	patch: UpdateUserTspBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/users/${encodeURIComponent(String(userId))}/tsp/${encodeURIComponent(String(tspId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteUserTspWirePath = NonNullable<paths["/users/{userId}/tsp/{tspId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /users/{userId}/tsp/{tspId}`
 *
 * Delete a user's TSP account
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `tsp:write:admin` `tsp:write` `tsp:delete:tsp_account` `tsp:delete:tsp_account:admin` and openapi_authorization: header `Authorization`
 */
export function deleteUserTsp(
	userId: DeleteUserTspWirePath["userId"],
	tspId: DeleteUserTspWirePath["tspId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/users/${encodeURIComponent(String(userId))}/tsp/${encodeURIComponent(String(tspId))}`,
		decode: async () => undefined,
	};
}

type ListUserUpcomingMeetingsWirePath = NonNullable<paths["/users/{userId}/upcoming_meetings"]["get"]["parameters"]["path"]>;

/** What {@link listUserUpcomingMeetings} resolves to. */
export type ListUserUpcomingMeetingsResponse =
	paths["/users/{userId}/upcoming_meetings"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/upcoming_meetings`
 *
 * List upcoming meetings
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `meeting:read` `meeting:read:admin` `meeting:read:list_upcoming_meetings` `meeting:read:list_upcoming_meetings:admin` and openapi_authorization: header `Authorization`
 */
export function listUserUpcomingMeetings(
	userId: ListUserUpcomingMeetingsWirePath["userId"],
): Operation<ListUserUpcomingMeetingsResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/upcoming_meetings`,
	};
}

type ListUserWebinarTemplatesWirePath = NonNullable<paths["/users/{userId}/webinar_templates"]["get"]["parameters"]["path"]>;

/** What {@link listUserWebinarTemplates} resolves to. */
export type ListUserWebinarTemplatesResponse =
	paths["/users/{userId}/webinar_templates"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/webinar_templates`
 *
 * List webinar templates
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read` `webinar:read:admin` `webinar:read:list_templates` `webinar:read:list_templates:admin` and openapi_authorization: header `Authorization`
 */
export function listUserWebinarTemplates(
	userId: ListUserWebinarTemplatesWirePath["userId"],
): Operation<ListUserWebinarTemplatesResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/webinar_templates`,
	};
}

type CreateUserWebinarTemplateWirePath = NonNullable<paths["/users/{userId}/webinar_templates"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createUserWebinarTemplate}. */
export type CreateUserWebinarTemplateBody = NonNullable<paths["/users/{userId}/webinar_templates"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createUserWebinarTemplate} resolves to. */
export type CreateUserWebinarTemplateResponse =
	paths["/users/{userId}/webinar_templates"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /users/{userId}/webinar_templates`
 *
 * Create a webinar template
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:write:template` `webinar:write:template:admin` and openapi_authorization: header `Authorization`
 */
export function createUserWebinarTemplate(
	userId: CreateUserWebinarTemplateWirePath["userId"],
	input: CreateUserWebinarTemplateBody,
): Operation<CreateUserWebinarTemplateResponse> {
	return {
		method: "POST",
		path: `/users/${encodeURIComponent(String(userId))}/webinar_templates`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ListUserWebinarsWirePath = NonNullable<paths["/users/{userId}/webinars"]["get"]["parameters"]["path"]>;

type ListUserWebinarsWireQuery = NonNullable<paths["/users/{userId}/webinars"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listUserWebinars}. */
export interface ListUserWebinarsQuery {
	/**
	 * The type of webinar. 
	 * * `scheduled` - All valid previous (unexpired) webinars, live webinars, and upcoming scheduled webinars. 
	 * * `upcoming` - All upcoming webinars, including live webinars.
	 */
	readonly type?: Sendable<ListUserWebinarsWireQuery["type"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListUserWebinarsWireQuery["page_size"]>;

	/** **Deprecated** We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination. */
	readonly pageNumber?: Sendable<ListUserWebinarsWireQuery["page_number"]>;

	/** Include Zoom events webinar in searches. The default is `true`. */
	readonly includeEventsWebinar?: Sendable<ListUserWebinarsWireQuery["include_events_webinar"]>;
}

/** What {@link listUserWebinars} resolves to. */
export type ListUserWebinarsResponse =
	paths["/users/{userId}/webinars"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users/{userId}/webinars`
 *
 * List webinars
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_webinars` `webinar:read:list_webinars:admin` and openapi_authorization: header `Authorization`
 */
export function listUserWebinars(
	userId: ListUserWebinarsWirePath["userId"],
	query: ListUserWebinarsQuery = {},
): Operation<ListUserWebinarsResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/webinars`,
		query: {
			type: query.type,
			page_size: query.pageSize,
			page_number: query.pageNumber,
			include_events_webinar: query.includeEventsWebinar,
		},
	};
}

type CreateUserWebinarWirePath = NonNullable<paths["/users/{userId}/webinars"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createUserWebinar}. */
export type CreateUserWebinarBody = NonNullable<paths["/users/{userId}/webinars"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createUserWebinar} resolves to. */
export type CreateUserWebinarResponse =
	paths["/users/{userId}/webinars"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /users/{userId}/webinars`
 *
 * Create a webinar
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:write:webinar` `webinar:write:webinar:admin` and openapi_authorization: header `Authorization`
 */
export function createUserWebinar(
	userId: CreateUserWebinarWirePath["userId"],
	input: CreateUserWebinarBody,
): Operation<CreateUserWebinarResponse> {
	return {
		method: "POST",
		path: `/users/${encodeURIComponent(String(userId))}/webinars`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}
