// @generated by dung beetle from ./tests/generator/fixtures/users.yaml. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import { readJson } from "../decode.js";
import { joined } from "../query.js";
import type { Operation, QueryValue } from "../operation.js";
import type { components, paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

/** `components.schemas.new-user` as the document declares it. */
export type NewUser = components["schemas"]["new-user"];

/** `components.schemas.User` as the document declares it. */
export type User = components["schemas"]["User"];

type ListUsersWireQuery = NonNullable<paths["/users"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listUsers}. */
export interface ListUsersQuery {
	/**
	 * One-based page of results.
	 *
	 * @deprecated
	 */
	readonly page?: Sendable<ListUsersWireQuery["page"]>;
	readonly perPage?: Sendable<ListUsersWireQuery["per_page"]>;
	readonly tag?: ListUsersWireQuery["tag"];
}

/** What {@link listUsers} resolves to. */
export type ListUsersResponse =
	paths["/users"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /users`
 *
 * List users.
 *
 * @remarks Reads the `x-request-id` header, which the client's headers or `RequestOptions.headers` carry.
 *
 * @security ApiKey: query parameter `api_key`, which needs a transport decorator since the client sends no query of its own
 */
export function listUsers(query: ListUsersQuery = {}): Operation<ListUsersResponse> {
	return {
		method: "GET",
		path: "/users",
		query: {
			page: query.page,
			per_page: query.perPage,
			tag: joined(query.tag, ","),
		},
	};
}

type CreateUserWireQuery = NonNullable<paths["/users"]["post"]["parameters"]["query"]>;

/** Query accepted by {@link createUser}. */
export interface CreateUserQuery {
	/** One-based page of results. */
	readonly page?: Sendable<CreateUserWireQuery["page"]>;
}

/** What {@link createUser} resolves to. */
export type CreateUserResponse =
	paths["/users"]["post"]["responses"][201]["content"]["application/json"]
	| undefined;

/**
 * `POST /users`
 *
 * @remarks Reads the `x-request-id` header, which the client's headers or `RequestOptions.headers` carry.
 *
 * @security ApiKey: query parameter `api_key`, which needs a transport decorator since the client sends no query of its own
 */
export function createUser(
	input: NewUser,
	query: CreateUserQuery = {},
): Operation<CreateUserResponse> {
	return {
		method: "POST",
		path: "/users",
		query: {
			page: query.page,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async (response) =>
			response.status === 202
				? undefined
				: readJson<CreateUserResponse>(response),
	};
}

type GetUserWirePath = NonNullable<paths["/users/{user_id}"]["get"]["parameters"]["path"]>;

/**
 * `GET /users/{user_id}`
 *
 * @security ApiKey: query parameter `api_key`, which needs a transport decorator since the client sends no query of its own
 */
export function getUser(userId: GetUserWirePath["user_id"]): Operation<User> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}`,
	};
}

type DeleteUserWirePath = NonNullable<paths["/users/{user_id}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /users/{user_id}`
 *
 * @security None. This endpoint overrides the document's requirement.
 *
 * @deprecated
 */
export function deleteUser(userId: DeleteUserWirePath["user_id"]): Operation<void> {
	return {
		method: "DELETE",
		path: `/users/${encodeURIComponent(String(userId))}`,
		decode: async () => undefined,
	};
}

type ListUserSessionsWirePath = NonNullable<paths["/users/{user_id}/sessions"]["get"]["parameters"]["path"]>;

/** What {@link listUserSessions} resolves to. */
export type ListUserSessionsResponse =
	paths["/users/{user_id}/sessions"]["get"]["responses"][200]["content"]["application/vnd.example+json"]
	| undefined;

/**
 * `GET /users/{user_id}/sessions`
 *
 * @remarks Reads the `session_hint` cookie, which a browser will not let `fetch` set. The document answers `2XX` with no body, which no status check can single out, so such a response fails to decode.
 *
 * @security ApiKey: query parameter `api_key`, which needs a transport decorator since the client sends no query of its own
 */
export function listUserSessions(
	userId: ListUserSessionsWirePath["user_id"],
): Operation<ListUserSessionsResponse> {
	return {
		method: "GET",
		path: `/users/${encodeURIComponent(String(userId))}/sessions`,
	};
}
