// @generated by dung beetle from https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue, RequestBody } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type GetWebinarWirePath = NonNullable<paths["/webinars/{webinarId}"]["get"]["parameters"]["path"]>;

type GetWebinarWireQuery = NonNullable<paths["/webinars/{webinarId}"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getWebinar}. */
export interface GetWebinarQuery {
	/** Unique identifier for an occurrence of a recurring webinar. [Recurring webinars](https://support.zoom.us/hc/en-us/articles/216354763-How-to-Schedule-A-Recurring-Webinar) can have a maximum of 50 occurrences. When you create a recurring Webinar using [**Create a webinar**](/docs/api-reference/zoom-api/methods#operation/webinarCreate) API, you can retrieve the Occurrence ID from the response of the API call. */
	readonly occurrenceId?: Sendable<GetWebinarWireQuery["occurrence_id"]>;

	/** Set the value of this field to `true` to view webinar details of all previous occurrences of a recurring webinar. */
	readonly showPreviousOccurrences?: Sendable<GetWebinarWireQuery["show_previous_occurrences"]>;
}

/** What {@link getWebinar} resolves to. */
export type GetWebinarResponse =
	paths["/webinars/{webinarId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}`
 *
 * Get a webinar
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:webinar` `webinar:read:webinar:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinar(
	webinarId: GetWebinarWirePath["webinarId"],
	query: GetWebinarQuery = {},
): Operation<GetWebinarResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}`,
		query: {
			occurrence_id: query.occurrenceId,
			show_previous_occurrences: query.showPreviousOccurrences,
		},
	};
}

type UpdateWebinarWirePath = NonNullable<paths["/webinars/{webinarId}"]["patch"]["parameters"]["path"]>;

type UpdateWebinarWireQuery = NonNullable<paths["/webinars/{webinarId}"]["patch"]["parameters"]["query"]>;

/** Query accepted by {@link updateWebinar}. */
export interface UpdateWebinarQuery {
	/** Webinar occurrence ID. Support change of agenda, start time, duration, and settings `host_video`, `panelist_video`, `hd_video, watermark`, `auto_recording`. */
	readonly occurrenceId?: Sendable<UpdateWebinarWireQuery["occurrence_id"]>;
}

/** Body accepted by {@link updateWebinar}. */
export type UpdateWebinarBody = NonNullable<paths["/webinars/{webinarId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /webinars/{webinarId}`
 *
 * Update a webinar
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:update:webinar` `webinar:update:webinar:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinar(
	webinarId: UpdateWebinarWirePath["webinarId"],
	patch: UpdateWebinarBody,
	query: UpdateWebinarQuery = {},
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}`,
		query: {
			occurrence_id: query.occurrenceId,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteWebinarWirePath = NonNullable<paths["/webinars/{webinarId}"]["delete"]["parameters"]["path"]>;

type DeleteWebinarWireQuery = NonNullable<paths["/webinars/{webinarId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteWebinar}. */
export interface DeleteWebinarQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<DeleteWebinarWireQuery["occurrence_id"]>;

	/**
	 * `true` - Notify panelists and registrants about the webinar cancellation via email. 
	 *
	 * `false` - Do not send any email notification to webinar registrants and panelists. 
	 *
	 * The default value of this field is `false`.
	 */
	readonly cancelWebinarReminder?: Sendable<DeleteWebinarWireQuery["cancel_webinar_reminder"]>;
}

/**
 * `DELETE /webinars/{webinarId}`
 *
 * Delete a webinar
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:delete:webinar` `webinar:delete:webinar:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinar(
	webinarId: DeleteWebinarWirePath["webinarId"],
	query: DeleteWebinarQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}`,
		query: {
			occurrence_id: query.occurrenceId,
			cancel_webinar_reminder: query.cancelWebinarReminder,
		},
		decode: async () => undefined,
	};
}

type CreateWebinarBatchRegistrantWirePath = NonNullable<paths["/webinars/{webinarId}/batch_registrants"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createWebinarBatchRegistrant}. */
export type CreateWebinarBatchRegistrantBody = NonNullable<paths["/webinars/{webinarId}/batch_registrants"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createWebinarBatchRegistrant} resolves to. */
export type CreateWebinarBatchRegistrantResponse =
	paths["/webinars/{webinarId}/batch_registrants"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/batch_registrants`
 *
 * Perform batch registration
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:write:batch_registrants` `webinar:write:batch_registrants:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarBatchRegistrant(
	webinarId: CreateWebinarBatchRegistrantWirePath["webinarId"],
	input: CreateWebinarBatchRegistrantBody,
): Operation<CreateWebinarBatchRegistrantResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/batch_registrants`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetWebinarBrandingWirePath = NonNullable<paths["/webinars/{webinarId}/branding"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarBranding} resolves to. */
export type GetWebinarBrandingResponse =
	paths["/webinars/{webinarId}/branding"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/branding`
 *
 * Get webinar's session branding
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read` `webinar:read:admin` `webinar:read:branding` `webinar:read:branding:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarBranding(
	webinarId: GetWebinarBrandingWirePath["webinarId"],
): Operation<GetWebinarBrandingResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding`,
	};
}

type CreateWebinarBrandingNameTagWirePath = NonNullable<paths["/webinars/{webinarId}/branding/name_tags"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createWebinarBrandingNameTag}. */
export type CreateWebinarBrandingNameTagBody = NonNullable<paths["/webinars/{webinarId}/branding/name_tags"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createWebinarBrandingNameTag} resolves to. */
export type CreateWebinarBrandingNameTagResponse =
	paths["/webinars/{webinarId}/branding/name_tags"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/branding/name_tags`
 *
 * Create a webinar's branding name tag
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:write:branding_name_tag` `webinar:write:branding_name_tag:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarBrandingNameTag(
	webinarId: CreateWebinarBrandingNameTagWirePath["webinarId"],
	input: CreateWebinarBrandingNameTagBody,
): Operation<CreateWebinarBrandingNameTagResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/name_tags`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type DeleteWebinarBrandingNameTagsWirePath = NonNullable<paths["/webinars/{webinarId}/branding/name_tags"]["delete"]["parameters"]["path"]>;

type DeleteWebinarBrandingNameTagsWireQuery = NonNullable<paths["/webinars/{webinarId}/branding/name_tags"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteWebinarBrandingNameTags}. */
export interface DeleteWebinarBrandingNameTagsQuery {
	/** A comma-separated list of the name tag IDs to delete. */
	readonly nameTagIds?: Sendable<DeleteWebinarBrandingNameTagsWireQuery["name_tag_ids"]>;
}

/**
 * `DELETE /webinars/{webinarId}/branding/name_tags`
 *
 * Delete a webinar's branding name tag
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:delete:branding_name_tag` `webinar:delete:branding_name_tag:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarBrandingNameTags(
	webinarId: DeleteWebinarBrandingNameTagsWirePath["webinarId"],
	query: DeleteWebinarBrandingNameTagsQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/name_tags`,
		query: {
			name_tag_ids: query.nameTagIds,
		},
		decode: async () => undefined,
	};
}

type UpdateWebinarBrandingNameTagWirePath = NonNullable<paths["/webinars/{webinarId}/branding/name_tags/{nameTagId}"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateWebinarBrandingNameTag}. */
export type UpdateWebinarBrandingNameTagBody = NonNullable<paths["/webinars/{webinarId}/branding/name_tags/{nameTagId}"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /webinars/{webinarId}/branding/name_tags/{nameTagId}`
 *
 * Update a webinar's branding name tag
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:update:branding_name_tag` `webinar:update:branding_name_tag:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarBrandingNameTag(
	webinarId: UpdateWebinarBrandingNameTagWirePath["webinarId"],
	nameTagId: UpdateWebinarBrandingNameTagWirePath["nameTagId"],
	patch: UpdateWebinarBrandingNameTagBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/name_tags/${encodeURIComponent(String(nameTagId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type CreateWebinarBrandingVirtualBackgroundWirePath = NonNullable<paths["/webinars/{webinarId}/branding/virtual_backgrounds"]["post"]["parameters"]["path"]>;

/** What {@link createWebinarBrandingVirtualBackground} resolves to. */
export type CreateWebinarBrandingVirtualBackgroundResponse =
	paths["/webinars/{webinarId}/branding/virtual_backgrounds"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/branding/virtual_backgrounds`
 *
 * Upload a webinar's branding virtual background
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:write:branding_virtual_background` `webinar:write:branding_virtual_background:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarBrandingVirtualBackground(
	webinarId: CreateWebinarBrandingVirtualBackgroundWirePath["webinarId"],
	body: RequestBody,
): Operation<CreateWebinarBrandingVirtualBackgroundResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/virtual_backgrounds`,
		headers: { "content-type": "multipart/form-data" },
		body,
	};
}

type UpdateWebinarBrandingVirtualBackgroundsWirePath = NonNullable<paths["/webinars/{webinarId}/branding/virtual_backgrounds"]["patch"]["parameters"]["path"]>;

type UpdateWebinarBrandingVirtualBackgroundsWireQuery = NonNullable<paths["/webinars/{webinarId}/branding/virtual_backgrounds"]["patch"]["parameters"]["query"]>;

/** Query accepted by {@link updateWebinarBrandingVirtualBackgrounds}. */
export interface UpdateWebinarBrandingVirtualBackgroundsQuery {
	/** The virtual background file ID to update. */
	readonly id?: Sendable<UpdateWebinarBrandingVirtualBackgroundsWireQuery["id"]>;

	/** Whether to set the virtual background file as the new default for all panelists. This includes panelists not currently assigned a default virtual background. */
	readonly setDefaultForAllPanelists?: Sendable<UpdateWebinarBrandingVirtualBackgroundsWireQuery["set_default_for_all_panelists"]>;
}

/**
 * `PATCH /webinars/{webinarId}/branding/virtual_backgrounds`
 *
 * Set webinar's default branding virtual background
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:update:branding_virtual_background` `webinar:update:branding_virtual_background:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarBrandingVirtualBackgrounds(
	webinarId: UpdateWebinarBrandingVirtualBackgroundsWirePath["webinarId"],
	query: UpdateWebinarBrandingVirtualBackgroundsQuery = {},
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/virtual_backgrounds`,
		query: {
			id: query.id,
			set_default_for_all_panelists: query.setDefaultForAllPanelists,
		},
		decode: async () => undefined,
	};
}

type DeleteWebinarBrandingVirtualBackgroundsWirePath = NonNullable<paths["/webinars/{webinarId}/branding/virtual_backgrounds"]["delete"]["parameters"]["path"]>;

type DeleteWebinarBrandingVirtualBackgroundsWireQuery = NonNullable<paths["/webinars/{webinarId}/branding/virtual_backgrounds"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteWebinarBrandingVirtualBackgrounds}. */
export interface DeleteWebinarBrandingVirtualBackgroundsQuery {
	/** A comma-separated list of the virtual background file IDs to delete. */
	readonly ids?: Sendable<DeleteWebinarBrandingVirtualBackgroundsWireQuery["ids"]>;
}

/**
 * `DELETE /webinars/{webinarId}/branding/virtual_backgrounds`
 *
 * Delete a webinar's branding virtual backgrounds
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:delete:branding_virtual_background` `webinar:delete:branding_virtual_background:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarBrandingVirtualBackgrounds(
	webinarId: DeleteWebinarBrandingVirtualBackgroundsWirePath["webinarId"],
	query: DeleteWebinarBrandingVirtualBackgroundsQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/virtual_backgrounds`,
		query: {
			ids: query.ids,
		},
		decode: async () => undefined,
	};
}

type UpdateWebinarBrandingWallpaperWirePath = NonNullable<paths["/webinars/{webinarId}/branding/wallpaper"]["post"]["parameters"]["path"]>;

/** What {@link updateWebinarBrandingWallpaper} resolves to. */
export type UpdateWebinarBrandingWallpaperResponse =
	paths["/webinars/{webinarId}/branding/wallpaper"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/branding/wallpaper`
 *
 * Upload a webinar's branding wallpaper
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:write:branding_wallpaper` `webinar:write:branding_wallpaper:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarBrandingWallpaper(
	webinarId: UpdateWebinarBrandingWallpaperWirePath["webinarId"],
	body: RequestBody,
): Operation<UpdateWebinarBrandingWallpaperResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/wallpaper`,
		headers: { "content-type": "multipart/form-data" },
		body,
	};
}

type DeleteWebinarBrandingWallpaperWirePath = NonNullable<paths["/webinars/{webinarId}/branding/wallpaper"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /webinars/{webinarId}/branding/wallpaper`
 *
 * Delete a webinar's branding wallpaper
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:delete:branding_wallpaper` `webinar:delete:branding_wallpaper:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarBrandingWallpaper(
	webinarId: DeleteWebinarBrandingWallpaperWirePath["webinarId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/branding/wallpaper`,
		decode: async () => undefined,
	};
}

type CreateWebinarInviteLinkWirePath = NonNullable<paths["/webinars/{webinarId}/invite_links"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createWebinarInviteLink}. */
export type CreateWebinarInviteLinkBody = NonNullable<paths["/webinars/{webinarId}/invite_links"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createWebinarInviteLink} resolves to. */
export type CreateWebinarInviteLinkResponse =
	paths["/webinars/{webinarId}/invite_links"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/invite_links`
 *
 * Create webinar's invite links
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:write:invite_links` `webinar:write:invite_links:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarInviteLink(
	webinarId: CreateWebinarInviteLinkWirePath["webinarId"],
	input: CreateWebinarInviteLinkBody,
): Operation<CreateWebinarInviteLinkResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/invite_links`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetWebinarJointokenLiveStreamingWirePath = NonNullable<paths["/webinars/{webinarId}/jointoken/live_streaming"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarJointokenLiveStreaming} resolves to. */
export type GetWebinarJointokenLiveStreamingResponse =
	paths["/webinars/{webinarId}/jointoken/live_streaming"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/jointoken/live_streaming`
 *
 * Get a webinar's join token for live streaming
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar_token:read:admin:live_streaming` `webinar_token:read:live_streaming` `webinar:read:live_streaming_token` `webinar:read:live_streaming_token:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarJointokenLiveStreaming(
	webinarId: GetWebinarJointokenLiveStreamingWirePath["webinarId"],
): Operation<GetWebinarJointokenLiveStreamingResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/jointoken/live_streaming`,
	};
}

type GetWebinarJointokenLocalArchivingWirePath = NonNullable<paths["/webinars/{webinarId}/jointoken/local_archiving"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarJointokenLocalArchiving} resolves to. */
export type GetWebinarJointokenLocalArchivingResponse =
	paths["/webinars/{webinarId}/jointoken/local_archiving"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/jointoken/local_archiving`
 *
 * Get a webinar's archive token for local archiving
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar_token:read:admin:local_archiving` `webinar:read:local_archiving_token:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarJointokenLocalArchiving(
	webinarId: GetWebinarJointokenLocalArchivingWirePath["webinarId"],
): Operation<GetWebinarJointokenLocalArchivingResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/jointoken/local_archiving`,
	};
}

type GetWebinarJointokenLocalRecordingWirePath = NonNullable<paths["/webinars/{webinarId}/jointoken/local_recording"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarJointokenLocalRecording} resolves to. */
export type GetWebinarJointokenLocalRecordingResponse =
	paths["/webinars/{webinarId}/jointoken/local_recording"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/jointoken/local_recording`
 *
 * Get a webinar's join token for local recording
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar_token:read:admin:local_recording` `webinar_token:read:local_recording` `webinar:read:local_recording_token` `webinar:read:local_recording_token:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarJointokenLocalRecording(
	webinarId: GetWebinarJointokenLocalRecordingWirePath["webinarId"],
): Operation<GetWebinarJointokenLocalRecordingResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/jointoken/local_recording`,
	};
}

type GetWebinarLivestreamWirePath = NonNullable<paths["/webinars/{webinarId}/livestream"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarLivestream} resolves to. */
export type GetWebinarLivestreamResponse =
	paths["/webinars/{webinarId}/livestream"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/livestream`
 *
 * Get live stream details
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:livestream` `webinar:read:livestream:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarLivestream(
	webinarId: GetWebinarLivestreamWirePath["webinarId"],
): Operation<GetWebinarLivestreamResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/livestream`,
	};
}

type UpdateWebinarLivestreamWirePath = NonNullable<paths["/webinars/{webinarId}/livestream"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateWebinarLivestream}. */
export type UpdateWebinarLivestreamBody = NonNullable<paths["/webinars/{webinarId}/livestream"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /webinars/{webinarId}/livestream`
 *
 * Update a live stream
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:update:livestream` `webinar:update:livestream:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarLivestream(
	webinarId: UpdateWebinarLivestreamWirePath["webinarId"],
	patch: UpdateWebinarLivestreamBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/livestream`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type UpdateWebinarLivestreamStatusWirePath = NonNullable<paths["/webinars/{webinarId}/livestream/status"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateWebinarLivestreamStatus}. */
export type UpdateWebinarLivestreamStatusBody = NonNullable<paths["/webinars/{webinarId}/livestream/status"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /webinars/{webinarId}/livestream/status`
 *
 * Update live stream status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:update:livestream_status` `webinar:update:livestream_status:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarLivestreamStatus(
	webinarId: UpdateWebinarLivestreamStatusWirePath["webinarId"],
	patch: UpdateWebinarLivestreamStatusBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/livestream/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type ListWebinarPanelistsWirePath = NonNullable<paths["/webinars/{webinarId}/panelists"]["get"]["parameters"]["path"]>;

/** What {@link listWebinarPanelists} resolves to. */
export type ListWebinarPanelistsResponse =
	paths["/webinars/{webinarId}/panelists"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/panelists`
 *
 * List panelists
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_panelists` `webinar:read:list_panelists:admin` and openapi_authorization: header `Authorization`
 */
export function listWebinarPanelists(
	webinarId: ListWebinarPanelistsWirePath["webinarId"],
): Operation<ListWebinarPanelistsResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/panelists`,
	};
}

type CreateWebinarPanelistWirePath = NonNullable<paths["/webinars/{webinarId}/panelists"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createWebinarPanelist}. */
export type CreateWebinarPanelistBody = NonNullable<paths["/webinars/{webinarId}/panelists"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createWebinarPanelist} resolves to. */
export type CreateWebinarPanelistResponse =
	paths["/webinars/{webinarId}/panelists"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/panelists`
 *
 * Add panelists
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:write:panelist` `webinar:write:panelist:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarPanelist(
	webinarId: CreateWebinarPanelistWirePath["webinarId"],
	input: CreateWebinarPanelistBody,
): Operation<CreateWebinarPanelistResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/panelists`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type DeleteWebinarPanelistsWirePath = NonNullable<paths["/webinars/{webinarId}/panelists"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /webinars/{webinarId}/panelists`
 *
 * Remove all panelists
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:delete:panelist` `webinar:delete:panelist:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarPanelists(
	webinarId: DeleteWebinarPanelistsWirePath["webinarId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/panelists`,
		decode: async () => undefined,
	};
}

type DeleteWebinarPanelistWirePath = NonNullable<paths["/webinars/{webinarId}/panelists/{panelistId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /webinars/{webinarId}/panelists/{panelistId}`
 *
 * Remove a panelist
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:delete:panelist` `webinar:delete:panelist:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarPanelist(
	webinarId: DeleteWebinarPanelistWirePath["webinarId"],
	panelistId: DeleteWebinarPanelistWirePath["panelistId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/panelists/${encodeURIComponent(String(panelistId))}`,
		decode: async () => undefined,
	};
}

type ListWebinarPollsWirePath = NonNullable<paths["/webinars/{webinarId}/polls"]["get"]["parameters"]["path"]>;

type ListWebinarPollsWireQuery = NonNullable<paths["/webinars/{webinarId}/polls"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listWebinarPolls}. */
export interface ListWebinarPollsQuery {
	/**
	 * Whether to query for polls with the **Anonymous** option enabled: 
	 * * `true` &mdash; Query for polls with the **Anonymous** option enabled. 
	 * * `false` &mdash; Do not query for polls with the **Anonymous** option enabled.
	 */
	readonly anonymous?: Sendable<ListWebinarPollsWireQuery["anonymous"]>;
}

/** What {@link listWebinarPolls} resolves to. */
export type ListWebinarPollsResponse =
	paths["/webinars/{webinarId}/polls"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/polls`
 *
 * List a webinar's polls 
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_polls` `webinar:read:list_polls:admin` and openapi_authorization: header `Authorization`
 */
export function listWebinarPolls(
	webinarId: ListWebinarPollsWirePath["webinarId"],
	query: ListWebinarPollsQuery = {},
): Operation<ListWebinarPollsResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/polls`,
		query: {
			anonymous: query.anonymous,
		},
	};
}

type CreateWebinarPollWirePath = NonNullable<paths["/webinars/{webinarId}/polls"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link createWebinarPoll}. */
export type CreateWebinarPollBody = NonNullable<paths["/webinars/{webinarId}/polls"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createWebinarPoll} resolves to. */
export type CreateWebinarPollResponse =
	paths["/webinars/{webinarId}/polls"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/polls`
 *
 * Create a webinar's poll
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:write:poll` `webinar:write:poll:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarPoll(
	webinarId: CreateWebinarPollWirePath["webinarId"],
	input: CreateWebinarPollBody,
): Operation<CreateWebinarPollResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/polls`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type GetWebinarPollWirePath = NonNullable<paths["/webinars/{webinarId}/polls/{pollId}"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarPoll} resolves to. */
export type GetWebinarPollResponse =
	paths["/webinars/{webinarId}/polls/{pollId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/polls/{pollId}`
 *
 * Get a webinar poll
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:poll` `webinar:read:poll:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarPoll(
	webinarId: GetWebinarPollWirePath["webinarId"],
	pollId: GetWebinarPollWirePath["pollId"],
): Operation<GetWebinarPollResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/polls/${encodeURIComponent(String(pollId))}`,
	};
}

type ReplaceWebinarPollWirePath = NonNullable<paths["/webinars/{webinarId}/polls/{pollId}"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link replaceWebinarPoll}. */
export type ReplaceWebinarPollBody = NonNullable<paths["/webinars/{webinarId}/polls/{pollId}"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /webinars/{webinarId}/polls/{pollId}`
 *
 * Update a webinar poll
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:update:poll` `webinar:update:poll:admin` and openapi_authorization: header `Authorization`
 */
export function replaceWebinarPoll(
	webinarId: ReplaceWebinarPollWirePath["webinarId"],
	pollId: ReplaceWebinarPollWirePath["pollId"],
	input: ReplaceWebinarPollBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/polls/${encodeURIComponent(String(pollId))}`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type DeleteWebinarPollWirePath = NonNullable<paths["/webinars/{webinarId}/polls/{pollId}"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /webinars/{webinarId}/polls/{pollId}`
 *
 * Delete a webinar poll
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:delete:poll` `webinar:delete:poll:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarPoll(
	webinarId: DeleteWebinarPollWirePath["webinarId"],
	pollId: DeleteWebinarPollWirePath["pollId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/polls/${encodeURIComponent(String(pollId))}`,
		decode: async () => undefined,
	};
}

type ListWebinarRegistrantsWirePath = NonNullable<paths["/webinars/{webinarId}/registrants"]["get"]["parameters"]["path"]>;

type ListWebinarRegistrantsWireQuery = NonNullable<paths["/webinars/{webinarId}/registrants"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link listWebinarRegistrants}. */
export interface ListWebinarRegistrantsQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<ListWebinarRegistrantsWireQuery["occurrence_id"]>;

	/**
	 * Query by the registrant's status. 
	 * * `pending` - The registration is pending. 
	 * * `approved` - The registrant is approved. 
	 * * `denied` - The registration is denied.
	 */
	readonly status?: Sendable<ListWebinarRegistrantsWireQuery["status"]>;

	/** The tracking source ID for the registrants. Useful if you share the webinar registration page in multiple locations. See [Creating source tracking links for webinar registration](https://support.zoom.us/hc/en-us/articles/360000315683-Creating-source-tracking-links-for-webinar-registration) for details. */
	readonly trackingSourceId?: Sendable<ListWebinarRegistrantsWireQuery["tracking_source_id"]>;

	/** The number of records returned within a single API call. */
	readonly pageSize?: Sendable<ListWebinarRegistrantsWireQuery["page_size"]>;

	/** **Deprecated** This field will be deprecated. We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination. */
	readonly pageNumber?: Sendable<ListWebinarRegistrantsWireQuery["page_number"]>;

	/** Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token's expiration period is 15 minutes. */
	readonly nextPageToken?: Sendable<ListWebinarRegistrantsWireQuery["next_page_token"]>;
}

/** What {@link listWebinarRegistrants} resolves to. */
export type ListWebinarRegistrantsResponse =
	paths["/webinars/{webinarId}/registrants"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/registrants`
 *
 * List webinar registrants
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_registrants` `webinar:read:list_registrants:admin` and openapi_authorization: header `Authorization`
 */
export function listWebinarRegistrants(
	webinarId: ListWebinarRegistrantsWirePath["webinarId"],
	query: ListWebinarRegistrantsQuery = {},
): Operation<ListWebinarRegistrantsResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants`,
		query: {
			occurrence_id: query.occurrenceId,
			status: query.status,
			tracking_source_id: query.trackingSourceId,
			page_size: query.pageSize,
			page_number: query.pageNumber,
			next_page_token: query.nextPageToken,
		},
	};
}

type CreateWebinarRegistrantWirePath = NonNullable<paths["/webinars/{webinarId}/registrants"]["post"]["parameters"]["path"]>;

type CreateWebinarRegistrantWireQuery = NonNullable<paths["/webinars/{webinarId}/registrants"]["post"]["parameters"]["query"]>;

/** Query accepted by {@link createWebinarRegistrant}. */
export interface CreateWebinarRegistrantQuery {
	/** A comma-separated list of webinar occurrence IDs. Get this value with the [Get a webinar](/docs/api/rest/reference/zoom-api/methods/#operation/webinar) API. Make sure the `registration_type` is 3 if updating multiple occurrences with this API. */
	readonly occurrenceIds?: Sendable<CreateWebinarRegistrantWireQuery["occurrence_ids"]>;
}

/** Body accepted by {@link createWebinarRegistrant}. */
export type CreateWebinarRegistrantBody = NonNullable<paths["/webinars/{webinarId}/registrants"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link createWebinarRegistrant} resolves to. */
export type CreateWebinarRegistrantResponse =
	paths["/webinars/{webinarId}/registrants"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/registrants`
 *
 * Add a webinar registrant
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:write:registrant` `webinar:write:registrant:admin` and openapi_authorization: header `Authorization`
 */
export function createWebinarRegistrant(
	webinarId: CreateWebinarRegistrantWirePath["webinarId"],
	input: CreateWebinarRegistrantBody,
	query: CreateWebinarRegistrantQuery = {},
): Operation<CreateWebinarRegistrantResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants`,
		query: {
			occurrence_ids: query.occurrenceIds,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ListWebinarRegistrantQuestionsWirePath = NonNullable<paths["/webinars/{webinarId}/registrants/questions"]["get"]["parameters"]["path"]>;

/** What {@link listWebinarRegistrantQuestions} resolves to. */
export type ListWebinarRegistrantQuestionsResponse =
	paths["/webinars/{webinarId}/registrants/questions"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/registrants/questions`
 *
 * List registration questions
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_registration_questions` `webinar:read:list_registration_questions:admin` and openapi_authorization: header `Authorization`
 */
export function listWebinarRegistrantQuestions(
	webinarId: ListWebinarRegistrantQuestionsWirePath["webinarId"],
): Operation<ListWebinarRegistrantQuestionsResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants/questions`,
	};
}

type UpdateWebinarRegistrantQuestionsWirePath = NonNullable<paths["/webinars/{webinarId}/registrants/questions"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateWebinarRegistrantQuestions}. */
export type UpdateWebinarRegistrantQuestionsBody = NonNullable<paths["/webinars/{webinarId}/registrants/questions"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /webinars/{webinarId}/registrants/questions`
 *
 * Update registration questions
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:update:registration_question` `webinar:update:registration_question:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarRegistrantQuestions(
	webinarId: UpdateWebinarRegistrantQuestionsWirePath["webinarId"],
	patch: UpdateWebinarRegistrantQuestionsBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants/questions`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type ReplaceWebinarRegistrantStatusWirePath = NonNullable<paths["/webinars/{webinarId}/registrants/status"]["put"]["parameters"]["path"]>;

type ReplaceWebinarRegistrantStatusWireQuery = NonNullable<paths["/webinars/{webinarId}/registrants/status"]["put"]["parameters"]["query"]>;

/** Query accepted by {@link replaceWebinarRegistrantStatus}. */
export interface ReplaceWebinarRegistrantStatusQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<ReplaceWebinarRegistrantStatusWireQuery["occurrence_id"]>;
}

/** Body accepted by {@link replaceWebinarRegistrantStatus}. */
export type ReplaceWebinarRegistrantStatusBody = NonNullable<paths["/webinars/{webinarId}/registrants/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /webinars/{webinarId}/registrants/status`
 *
 * Update registrant's status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:update:registrant_status` `webinar:update:registrant_status:admin` and openapi_authorization: header `Authorization`
 */
export function replaceWebinarRegistrantStatus(
	webinarId: ReplaceWebinarRegistrantStatusWirePath["webinarId"],
	input: ReplaceWebinarRegistrantStatusBody,
	query: ReplaceWebinarRegistrantStatusQuery = {},
): Operation<void> {
	return {
		method: "PUT",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants/status`,
		query: {
			occurrence_id: query.occurrenceId,
		},
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type GetWebinarRegistrantWirePath = NonNullable<paths["/webinars/{webinarId}/registrants/{registrantId}"]["get"]["parameters"]["path"]>;

type GetWebinarRegistrantWireQuery = NonNullable<paths["/webinars/{webinarId}/registrants/{registrantId}"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getWebinarRegistrant}. */
export interface GetWebinarRegistrantQuery {
	/** The meeting or webinar occurrence ID. */
	readonly occurrenceId?: Sendable<GetWebinarRegistrantWireQuery["occurrence_id"]>;
}

/** What {@link getWebinarRegistrant} resolves to. */
export type GetWebinarRegistrantResponse =
	paths["/webinars/{webinarId}/registrants/{registrantId}"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/registrants/{registrantId}`
 *
 * Get a webinar registrant
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:registrant` `webinar:read:registrant:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarRegistrant(
	webinarId: GetWebinarRegistrantWirePath["webinarId"],
	registrantId: GetWebinarRegistrantWirePath["registrantId"],
	query: GetWebinarRegistrantQuery = {},
): Operation<GetWebinarRegistrantResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants/${encodeURIComponent(String(registrantId))}`,
		query: {
			occurrence_id: query.occurrenceId,
		},
	};
}

type DeleteWebinarRegistrantWirePath = NonNullable<paths["/webinars/{webinarId}/registrants/{registrantId}"]["delete"]["parameters"]["path"]>;

type DeleteWebinarRegistrantWireQuery = NonNullable<paths["/webinars/{webinarId}/registrants/{registrantId}"]["delete"]["parameters"]["query"]>;

/** Query accepted by {@link deleteWebinarRegistrant}. */
export interface DeleteWebinarRegistrantQuery {
	/** The webinar occurrence ID. */
	readonly occurrenceId?: Sendable<DeleteWebinarRegistrantWireQuery["occurrence_id"]>;
}

/**
 * `DELETE /webinars/{webinarId}/registrants/{registrantId}`
 *
 * Delete a webinar registrant
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:delete:registrant` `webinar:delete:registrant:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarRegistrant(
	webinarId: DeleteWebinarRegistrantWirePath["webinarId"],
	registrantId: DeleteWebinarRegistrantWirePath["registrantId"],
	query: DeleteWebinarRegistrantQuery = {},
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/registrants/${encodeURIComponent(String(registrantId))}`,
		query: {
			occurrence_id: query.occurrenceId,
		},
		decode: async () => undefined,
	};
}

type SipDialingWebinarWirePath = NonNullable<paths["/webinars/{webinarId}/sip_dialing"]["post"]["parameters"]["path"]>;

/** Body accepted by {@link sipDialingWebinar}. */
export type SipDialingWebinarBody = NonNullable<paths["/webinars/{webinarId}/sip_dialing"]["post"]["requestBody"]>["content"]["application/json"];

/** What {@link sipDialingWebinar} resolves to. */
export type SipDialingWebinarResponse =
	paths["/webinars/{webinarId}/sip_dialing"]["post"]["responses"][201]["content"]["application/json"];

/**
 * `POST /webinars/{webinarId}/sip_dialing`
 *
 * Get a webinar SIP URI with passcode
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:sip_dialing` `webinar:write:admin:sip_dialing` `webinar:write:sip_dialing` `webinar:write:sip_dialing:admin` and openapi_authorization: header `Authorization`
 */
export function sipDialingWebinar(
	webinarId: SipDialingWebinarWirePath["webinarId"],
	input: SipDialingWebinarBody,
): Operation<SipDialingWebinarResponse> {
	return {
		method: "POST",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/sip_dialing`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
	};
}

type ReplaceWebinarStatusWirePath = NonNullable<paths["/webinars/{webinarId}/status"]["put"]["parameters"]["path"]>;

/** Body accepted by {@link replaceWebinarStatus}. */
export type ReplaceWebinarStatusBody = NonNullable<paths["/webinars/{webinarId}/status"]["put"]["requestBody"]>["content"]["application/json"];

/**
 * `PUT /webinars/{webinarId}/status`
 *
 * Update webinar status
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write:admin` `webinar:write` `webinar:update:status` `webinar:update:status:admin` and openapi_authorization: header `Authorization`
 */
export function replaceWebinarStatus(
	webinarId: ReplaceWebinarStatusWirePath["webinarId"],
	input: ReplaceWebinarStatusBody,
): Operation<void> {
	return {
		method: "PUT",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/status`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(input),
		decode: async () => undefined,
	};
}

type GetWebinarSurveyWirePath = NonNullable<paths["/webinars/{webinarId}/survey"]["get"]["parameters"]["path"]>;

/** What {@link getWebinarSurvey} resolves to. */
export type GetWebinarSurveyResponse =
	paths["/webinars/{webinarId}/survey"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/survey`
 *
 * Get a webinar survey
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:survey` `webinar:read:survey:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarSurvey(
	webinarId: GetWebinarSurveyWirePath["webinarId"],
): Operation<GetWebinarSurveyResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/survey`,
	};
}

type UpdateWebinarSurveyWirePath = NonNullable<paths["/webinars/{webinarId}/survey"]["patch"]["parameters"]["path"]>;

/** Body accepted by {@link updateWebinarSurvey}. */
export type UpdateWebinarSurveyBody = NonNullable<paths["/webinars/{webinarId}/survey"]["patch"]["requestBody"]>["content"]["application/json"];

/**
 * `PATCH /webinars/{webinarId}/survey`
 *
 * Update a webinar survey
 *
 * @remarks The document marks this body optional; it is required here.
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:update:survey` `webinar:update:survey:admin` and openapi_authorization: header `Authorization`
 */
export function updateWebinarSurvey(
	webinarId: UpdateWebinarSurveyWirePath["webinarId"],
	patch: UpdateWebinarSurveyBody,
): Operation<void> {
	return {
		method: "PATCH",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/survey`,
		headers: { "content-type": "application/json" },
		body: JSON.stringify(patch),
		decode: async () => undefined,
	};
}

type DeleteWebinarSurveyWirePath = NonNullable<paths["/webinars/{webinarId}/survey"]["delete"]["parameters"]["path"]>;

/**
 * `DELETE /webinars/{webinarId}/survey`
 *
 * Delete a webinar survey
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:write` `webinar:write:admin` `webinar:delete:survey` `webinar:delete:survey:admin` and openapi_authorization: header `Authorization`
 */
export function deleteWebinarSurvey(
	webinarId: DeleteWebinarSurveyWirePath["webinarId"],
): Operation<void> {
	return {
		method: "DELETE",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/survey`,
		decode: async () => undefined,
	};
}

type GetWebinarTokenWirePath = NonNullable<paths["/webinars/{webinarId}/token"]["get"]["parameters"]["path"]>;

type GetWebinarTokenWireQuery = NonNullable<paths["/webinars/{webinarId}/token"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getWebinarToken}. */
export interface GetWebinarTokenQuery {
	/**
	 * The webinar token type: 
	 * * `closed_caption_token` &mdash; The third-party closed caption API token. 
	 *
	 * This defaults to `closed_caption_token`.
	 */
	readonly type?: Sendable<GetWebinarTokenWireQuery["type"]>;
}

/** What {@link getWebinarToken} resolves to. */
export type GetWebinarTokenResponse =
	paths["/webinars/{webinarId}/token"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/token`
 *
 * Get webinar's token
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read` `webinar:read:admin` `webinar:read:token` `webinar:read:token:admin` and openapi_authorization: header `Authorization`
 */
export function getWebinarToken(
	webinarId: GetWebinarTokenWirePath["webinarId"],
	query: GetWebinarTokenQuery = {},
): Operation<GetWebinarTokenResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/token`,
		query: {
			type: query.type,
		},
	};
}

type ListWebinarTrackingSourcesWirePath = NonNullable<paths["/webinars/{webinarId}/tracking_sources"]["get"]["parameters"]["path"]>;

/** What {@link listWebinarTrackingSources} resolves to. */
export type ListWebinarTrackingSourcesResponse =
	paths["/webinars/{webinarId}/tracking_sources"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /webinars/{webinarId}/tracking_sources`
 *
 * Get webinar tracking sources
 *
 * @security openapi_oauth: OAuth2, token from , sent as `authorization: Bearer <token>`, scopes `webinar:read:admin` `webinar:read` `webinar:read:list_tracking_sources` `webinar:read:list_tracking_sources:admin` and openapi_authorization: header `Authorization`
 */
export function listWebinarTrackingSources(
	webinarId: ListWebinarTrackingSourcesWirePath["webinarId"],
): Operation<ListWebinarTrackingSourcesResponse> {
	return {
		method: "GET",
		path: `/webinars/${encodeURIComponent(String(webinarId))}/tracking_sources`,
	};
}
