import type {
	NormalizedDocument,
	SpecApiKeyScheme,
	SpecOperation,
	SpecParameter,
	SpecResponse,
	SpecSecurityRequirement,
	SpecSecurityScheme,
} from "./model.js";
import { parameterName, typeName } from "./names.js";
import {
	isJson,
	serialisationOf,
	type PlannedModule,
	type PlannedOperation,
} from "./plan.js";

// Writes the source a reader opens. Everything here is text, so the tests that
// matter are the golden file (does it read as hand-written) and the typecheck
// (does it compile against the real Operation).

/** Marks a file as this generator's to overwrite. */
export const BANNER_MARK = "@generated by dung beetle";

export interface EmitOptions {
	/** Where the document came from, named in the banner. */
	readonly spec: string;

	/**
	 * Module exporting `Operation`, `RequestBody` and `readJson`. Left unset,
	 * generated modules import from this template's own `src/`, which is what a
	 * copied runtime wants.
	 */
	readonly runtimeImport?: string;

	/** Module `openapi-typescript` writes its types to. */
	readonly schemaImport?: string;
}

interface Runtime {
	readonly operation: string;
	readonly decode: string;
	readonly query: string;
	readonly schema: string;
}

function runtimeOf(options: EmitOptions): Runtime {
	return {
		operation: options.runtimeImport ?? "../operation.js",
		decode: options.runtimeImport ?? "../decode.js",
		query: options.runtimeImport ?? "../query.js",
		schema: options.schemaImport ?? "../schema.js",
	};
}

/** The source of one resource module. */
export function emitModule(
	module: PlannedModule,
	document: NormalizedDocument,
	options: EmitOptions
): string {
	const runtime = runtimeOf(options);
	const blocks = [
		banner(options.spec),
		imports(module, runtime),
		sendable(module),
		...module.schemas.map(
			(schema) =>
				`/** \`components.schemas.${schema.component}\` as the document declares it. */\nexport type ${schema.name} = components["schemas"]["${schema.component}"];`
		),
		...module.operations.map((operation) => emitOperation(operation, document)),
	];

	return `${blocks.filter((block) => block.length > 0).join("\n\n")}\n`;
}

/**
 * Documents describe query parameters this client cannot put on a URL: Stripe
 * types `created` as a number or an object of comparisons, and sends the object
 * form as `created[gte]=`, which is several keys rather than one value. Narrowing
 * each property to what `buildUrl` builds keeps the forms that work and turns the
 * rest into `never`, so the module compiles and the impossible call is refused at
 * the call site rather than silently sent wrong.
 */
function sendable(module: PlannedModule): string {
	const needed = module.operations.some((operation) =>
		operation.spec.queryParameters.some(
			(parameter) => serialisationOf(parameter).kind === "repeat"
		)
	);

	return needed
		? "/** The part of a documented query type that this client can put on a URL. */\ntype Sendable<T> = Extract<T, QueryValue>;"
		: "";
}

function banner(spec: string): string {
	return [
		`// ${BANNER_MARK} from ${spec}. Do not edit.`,
		"//",
		"// Re-running the generator rewrites this file. A resource module without",
		"// this banner is left alone, so hand-written ones are safe here.",
	].join("\n");
}

function imports(module: PlannedModule, runtime: Runtime): string {
	const operations = module.operations;
	const types = ["Operation"];
	const lines: string[] = [];

	if (operations.some((operation) => decodeProperty(operation)?.includes("readJson"))) {
		lines.push(`import { readJson } from "${runtime.decode}";`);
	}

	const builders = ["deepObject", "joined"].filter((builder) =>
		operations.some((operation) =>
			operation.spec.queryParameters.some(
				(parameter) => serialisationOf(parameter).kind === builder
			)
		)
	);
	if (builders.length > 0) {
		lines.push(`import { ${builders.join(", ")} } from "${runtime.query}";`);
	}
	if (operations.some((operation) => operation.spec.requestBody && !operation.bodyType)) {
		types.push("RequestBody");
	}
	if (
		operations.some((operation) =>
			operation.spec.queryParameters.some(
				(parameter) => serialisationOf(parameter).kind === "repeat"
			)
		)
	) {
		types.push("QueryValue");
	}
	lines.push(`import type { ${types.sort().join(", ")} } from "${runtime.operation}";`);

	const usesPaths = operations.some(
		(operation) =>
			operation.spec.pathParameters.length > 0 ||
			operation.spec.queryParameters.length > 0 ||
			operation.bodyType?.declared === true ||
			operation.resultType.declared
	);
	const schemaTypes = [
		module.schemas.length > 0 ? "components" : undefined,
		usesPaths ? "paths" : undefined,
	].filter((type) => type !== undefined);

	if (schemaTypes.length > 0) {
		lines.push(`import type { ${schemaTypes.join(", ")} } from "${runtime.schema}";`);
	}
	for (const borrowed of module.borrowed) {
		lines.push(`import type { ${borrowed.name} } from "./${borrowed.from}.js";`);
	}

	return lines.join("\n");
}

function emitOperation(planned: PlannedOperation, document: NormalizedDocument): string {
	const { spec } = planned;
	const blocks: string[] = [];

	// The indexed access into `paths` is long, so each operation names the one
	// it reaches through rather than repeating it in every signature.
	if (spec.pathParameters.length > 0) {
		blocks.push(
			`type ${wireName(planned, "Path")} = NonNullable<${chain(spec)}["parameters"]["path"]>;`
		);
	}
	if (planned.queryType) {
		blocks.push(
			`type ${wireName(planned, "Query")} = NonNullable<${chain(spec)}["parameters"]["query"]>;`
		);
		blocks.push(emitQuery(planned, planned.queryType));
	}
	if (planned.bodyType?.declared) {
		blocks.push(
			`/** Body accepted by {@link ${planned.name}}. */\nexport type ${planned.bodyType.name} = ${bodyExpression(spec)};`
		);
	}
	if (planned.resultType.declared) {
		blocks.push(
			`/** What {@link ${planned.name}} resolves to. */\nexport type ${planned.resultType.name} =\n\t${resultExpression(planned)};`
		);
	}
	blocks.push(emitFunction(planned, document));

	return blocks.join("\n\n");
}

function emitQuery(planned: PlannedOperation, name: string): string {
	const wire = wireName(planned, "Query");
	const properties = planned.spec.queryParameters.map((parameter, index) => {
		const described = parameter.description !== undefined || parameter.deprecated;
		// A described property gets a blank line above it so its comment reads
		// as its own, except at the top of the interface.
		const spacing = described && index > 0 ? "\n" : "";
		const documentation = described
			? `${indent(comment(propertyDocumentation(parameter)), 1)}\n`
			: "";
		const optional = parameter.required ? "" : "?";

		// Only a value going straight onto the URL has to be one `buildUrl`
		// accepts; `joined` and `deepObject` take the shape the document declared.
		const declared = `${wire}[${JSON.stringify(parameter.name)}]`;
		const type =
			serialisationOf(parameter).kind === "repeat" ? `Sendable<${declared}>` : declared;

		return `${spacing}${documentation}\treadonly ${parameterName(parameter.name)}${optional}: ${type};`;
	});

	return [
		`/** Query accepted by {@link ${planned.name}}. */`,
		`export interface ${name} {`,
		properties.join("\n"),
		"}",
	].join("\n");
}

function propertyDocumentation(parameter: SpecParameter): string {
	return [parameter.description, parameter.deprecated ? "@deprecated" : undefined]
		.filter((part) => part !== undefined)
		.join("\n\n");
}

function emitFunction(planned: PlannedOperation, document: NormalizedDocument): string {
	const { spec } = planned;
	const parameters: string[] = spec.pathParameters.map(
		(parameter) =>
			`${parameterName(parameter.name)}: ${wireName(planned, "Path")}[${JSON.stringify(parameter.name)}]`
	);

	if (spec.requestBody) {
		parameters.push(
			planned.bodyType
				? `${bodyArgument(spec)}: ${planned.bodyType.name}`
				: "body: RequestBody"
		);
	}
	if (planned.queryType) {
		const required = spec.queryParameters.some((parameter) => parameter.required);
		parameters.push(`query: ${planned.queryType}${required ? "" : " = {}"}`);
	}

	const opening = `export function ${planned.name}(`;
	const closing = `): Operation<${planned.resultType.name}> {`;
	const inline = `${opening}${parameters.join(", ")}${closing}`;
	// Long signatures wrap one parameter per line, the way the hand-written
	// resource module in this template does.
	const signature =
		inline.length <= 88
			? inline
			: [opening, ...parameters.map((parameter) => `\t${parameter},`), closing].join("\n");

	return [
		documentation(planned, document),
		signature,
		"\treturn {",
		indent(operationLiteral(planned), 2),
		"\t};",
		"}",
	]
		.filter((part) => part.length > 0)
		.join("\n");
}

function operationLiteral(planned: PlannedOperation): string {
	const { spec } = planned;
	const lines = [`method: "${spec.method}",`, `path: ${pathLiteral(spec)},`];

	if (spec.queryParameters.length > 0) {
		lines.push("query: {");
		for (const parameter of spec.queryParameters) {
			lines.push(`\t${queryEntry(parameter)}`);
		}
		lines.push("},");
	}
	if (spec.requestBody) {
		lines.push(`headers: { "content-type": "${spec.requestBody.contentType}" },`);
		lines.push(
			isJson(spec.requestBody.contentType)
				? `body: JSON.stringify(${bodyArgument(spec)}),`
				: "body,"
		);
	}

	const decode = decodeProperty(planned);
	if (decode) {
		lines.push(decode);
	}

	return lines.join("\n");
}

/**
 * A `decode` only where the default JSON read would be wrong: a body that is
 * never sent, or a mix where some 2xx statuses carry one and others do not.
 */
function decodeProperty(planned: PlannedOperation): string | undefined {
	if (planned.spec.successes.length === 0 || planned.contentResponses.length === 0) {
		return planned.spec.successes.length === 0
			? undefined
			: "decode: async () => undefined,";
	}

	const empty = planned.emptyResponses
		.map((response) => response.status)
		.filter((status) => /^\d+$/u.test(status));

	if (empty.length === 0) {
		return undefined;
	}

	const test =
		empty.length === 1
			? `response.status === ${empty[0]}`
			: `[${empty.join(", ")}].includes(response.status)`;

	return [
		"decode: async (response) =>",
		`\t${test}`,
		"\t\t? undefined",
		`\t\t: readJson<${planned.resultType.name}>(response),`,
	].join("\n");
}

/** One entry of the query object, built the way the document asks for it. */
function queryEntry(parameter: SpecParameter): string {
	const property = `query.${parameterName(parameter.name)}`;
	const serialisation = serialisationOf(parameter);

	switch (serialisation.kind) {
	case "joined":
		return `${key(parameter.name)}: joined(${property}, ${JSON.stringify(serialisation.separator)}),`;
	case "deepObject":
		return `...deepObject(${JSON.stringify(parameter.name)}, ${property}),`;
	default:
		return `${key(parameter.name)}: ${property},`;
	}
}

function pathLiteral(operation: SpecOperation): string {
	if (operation.pathParameters.length === 0) {
		return `"${operation.path}"`;
	}

	const interpolated = operation.pathParameters.reduce(
		(path, parameter) =>
			path.replace(
				`{${parameter.name}}`,
				`\${encodeURIComponent(String(${parameterName(parameter.name)}))}`
			),
		operation.path
	);

	return `\`${interpolated}\``;
}

function bodyArgument(operation: SpecOperation): string {
	return operation.method === "PATCH" ? "patch" : "input";
}

function chain(operation: SpecOperation): string {
	return `paths["${operation.path}"]["${operation.method.toLowerCase()}"]`;
}

/** Name of the unexported alias for one slot of an operation's parameters. */
function wireName(planned: PlannedOperation, kind: "Path" | "Query"): string {
	return `${typeName(planned.name)}Wire${kind}`;
}

function bodyExpression(operation: SpecOperation): string {
	const contentType = operation.requestBody?.contentType ?? "application/json";

	return `NonNullable<${chain(operation)}["requestBody"]>["content"][${JSON.stringify(contentType)}]`;
}

function responseExpression(operation: SpecOperation, response: SpecResponse): string {
	const status = /^\d+$/u.test(response.status)
		? response.status
		: JSON.stringify(response.status);

	return `${chain(operation)}["responses"][${status}]["content"][${JSON.stringify(response.contentType ?? "")}]`;
}

function resultExpression(planned: PlannedOperation): string {
	const parts = planned.contentResponses.map((response) =>
		responseExpression(planned.spec, response)
	);

	if (planned.emptyResponses.length > 0) {
		parts.push("undefined");
	}

	return parts.join("\n\t| ");
}

function documentation(planned: PlannedOperation, document: NormalizedDocument): string {
	const { spec } = planned;
	const lines: string[] = [`\`${spec.method} ${spec.path}\``];
	const prose = spec.summary ?? firstParagraph(spec.description);

	if (prose) {
		lines.push("", prose);
	}

	const remarks = notes(planned);
	if (remarks.length > 0) {
		lines.push("", `@remarks ${remarks.join(" ")}`);
	}
	for (const line of securityLines(spec, document)) {
		lines.push("", line);
	}
	if (spec.deprecated) {
		lines.push("", "@deprecated");
	}

	return comment(lines.join("\n"));
}

function notes(planned: PlannedOperation): readonly string[] {
	const { spec } = planned;
	const remarks: string[] = [];

	if (spec.headerParameters.length > 0) {
		const named = list(spec.headerParameters.map((parameter) => `\`${parameter.name}\``));
		const one = spec.headerParameters.length === 1;

		remarks.push(
			`Reads the ${named} header${one ? "" : "s"}, which the client's headers or \`RequestOptions.headers\` carry.`
		);
	}
	if (spec.cookieParameters.length > 0) {
		remarks.push(
			`Reads the ${list(spec.cookieParameters.map((parameter) => `\`${parameter.name}\``))} cookie, which a browser will not let \`fetch\` set.`
		);
	}
	if (planned.awkwardQuery.length > 0) {
		remarks.push(
			`The document serialises ${list(planned.awkwardQuery.map((name) => `\`${name}\``))} in a way no URL this client builds can carry, so ${planned.awkwardQuery.length > 1 ? "those parameters are" : "that parameter is"} sent as one repeated key each.`
		);
	}
	if (planned.spec.successes.length === 0) {
		remarks.push(
			"The document declares no 2xx response, so the result is `unknown` and the body is read as JSON."
		);
	}

	const wildcards = planned.emptyResponses.filter(
		(response) => !/^\d+$/u.test(response.status)
	);
	if (planned.contentResponses.length > 0 && wildcards.length > 0) {
		remarks.push(
			`The document answers ${list(wildcards.map((response) => `\`${response.status}\``))} with no body, which no status check can single out, so such a response fails to decode.`
		);
	}
	if (spec.requestBody && !spec.requestBody.required) {
		remarks.push("The document marks this body optional; it is required here.");
	}

	return remarks;
}

function securityLines(
	operation: SpecOperation,
	document: NormalizedDocument
): readonly string[] {
	const requirements = operation.security ?? document.security;

	if (operation.security?.length === 0) {
		return ["@security None. This endpoint overrides the document's requirement."];
	}
	if (requirements.length === 0) {
		return [];
	}

	return requirements.map((requirement) => `@security ${describe(requirement, document)}`);
}

function describe(
	requirement: SpecSecurityRequirement,
	document: NormalizedDocument
): string {
	const parts = Object.entries(requirement).map(([name, scopes]) => {
		const scheme = document.securitySchemes.find((candidate) => candidate.name === name);
		const described = scheme ? describeScheme(scheme) : "not declared in the document";
		const scoped = scopes.length > 0 ? `, scopes ${scopes.map((scope) => `\`${scope}\``).join(" ")}` : "";

		return `${name}: ${described}${scoped}`;
	});

	return parts.join(" and ");
}

function describeScheme(scheme: SpecSecurityScheme): string {
	switch (scheme.kind) {
	case "http":
		return scheme.scheme === "basic"
			? "header `authorization: Basic <base64 of user:password>`"
			: `header \`authorization: ${titleCase(scheme.scheme)} <credentials>\``;
	case "apiKey":
		return describeApiKey(scheme);
	case "oauth2":
		return `OAuth2, token from ${scheme.flows.map((flow) => flow.tokenUrl ?? flow.authorizationUrl ?? "the flow's own URL").join(" or ")}, sent as \`authorization: Bearer <token>\``;
	case "openIdConnect":
		return `OpenID Connect, discovery at ${scheme.discoveryUrl}`;
	case "mutualTLS":
		return "a client certificate, which the transport configures";
	}
}

/**
 * The one fact only the document holds: where the credential goes and under
 * exactly what name. `X-API-Key` against `api-key` against `apikey` is a real
 * debugging session.
 */
function describeApiKey(scheme: SpecApiKeyScheme): string {
	switch (scheme.in) {
	case "header":
		return `header \`${scheme.parameterName}\``;
	case "query":
		return `query parameter \`${scheme.parameterName}\`, which needs a transport decorator since the client sends no query of its own`;
	case "cookie":
		return `cookie \`${scheme.parameterName}\`, which a browser will not let \`fetch\` set`;
	}
}

function firstParagraph(text: string | undefined): string | undefined {
	return text?.split(/\n\s*\n/u)[0]?.trim() || undefined;
}

/**
 * A TSDoc block. A description containing a comment terminator would close the
 * block early, so the star before the slash is escaped.
 */
function comment(body: string): string {
	const lines = body.replace(/\*\//gu, "*\\/").split("\n");

	if (lines.length === 1) {
		return `/** ${lines[0]} */`;
	}

	return ["/**", ...lines.map((line) => (line ? ` * ${line}` : " *")), " */"].join("\n");
}

function indent(text: string, depth: number): string {
	const tabs = "\t".repeat(depth);

	return text
		.split("\n")
		.map((line) => (line ? `${tabs}${line}` : line))
		.join("\n");
}

/** An object key, quoted only when it has to be. */
function key(name: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(name) ? name : JSON.stringify(name);
}

function list(items: readonly string[]): string {
	if (items.length <= 1) {
		return items.join("");
	}

	return `${items.slice(0, -1).join(", ")} and ${items.at(-1) ?? ""}`;
}

/** `bearer` to `Bearer`, the casing RFC 7235 writes the scheme in. */
function titleCase(value: string): string {
	return `${value.slice(0, 1).toUpperCase()}${value.slice(1)}`;
}
