// @generated by dung beetle from ./tests/generator/fixtures/users.yaml. Do not edit.
//
// Every type the document declares. Resource modules alias into it, so a
// name here is only public where one of them exports it.

export interface paths {
    readonly "/users": {
        readonly parameters: {
            readonly query?: {
                /** @description One-based page of results. */
                readonly page?: number;
            };
            readonly header?: {
                readonly "x-request-id"?: string;
                readonly Accept?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List users. */
        readonly get: operations["read_users_users__get"];
        readonly put?: never;
        readonly post: operations["create_user_users__post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/users/{user_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["read_user_users__user_id__get"];
        readonly put?: never;
        readonly post?: never;
        /** @deprecated */
        readonly delete: operations["delete_user_users__user_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/users/{user_id}/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["list_sessions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly User: {
            readonly id?: string;
            readonly name?: string;
        };
        readonly Session: {
            readonly id?: string;
        };
        readonly Problem: {
            readonly detail?: string;
        };
        readonly "new-user": {
            readonly name: string;
            readonly tags?: readonly string[];
        };
    };
    responses: {
        /** @description One user. */
        readonly User: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["User"];
            };
        };
    };
    parameters: {
        readonly PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly read_users_users__get: {
        readonly parameters: {
            readonly query?: {
                /**
                 * @deprecated
                 * @description One-based page of results.
                 */
                readonly page?: number;
                readonly per_page?: components["parameters"]["PerPage"];
                readonly tag?: readonly string[];
            };
            readonly header?: {
                readonly "x-request-id"?: string;
                readonly Accept?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description One page of users. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly data?: readonly components["schemas"]["User"][];
                    };
                };
            };
        };
    };
    readonly create_user_users__post: {
        readonly parameters: {
            readonly query?: {
                /** @description One-based page of results. */
                readonly page?: number;
            };
            readonly header?: {
                readonly "x-request-id"?: string;
                readonly Accept?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "text/plain": string;
                readonly "application/json": components["schemas"]["new-user"];
            };
        };
        readonly responses: {
            /** @description Created. */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["User"];
                };
            };
            /** @description Queued for creation. */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly read_user_users__user_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: components["responses"]["User"];
        };
    };
    readonly delete_user_users__user_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Deleted. */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such user. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly list_sessions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: {
                readonly session_hint?: string;
            };
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The user's sessions. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/vnd.example+json": readonly components["schemas"]["Session"][];
                };
            };
            /** @description Anything else that worked. */
            readonly "2XX": {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
